std = 'lua51'

exclude_files = {
    'libs/',
}

-- https://luacheck.readthedocs.io/en/stable/warnings.html#list-of-warnings
ignore = {
    '211/F', -- unused local variable 'F'
    '211/C', -- Unused local variable 'C'
    '211/L', -- unused local variable 'L'
    '212/self', -- unused argument 'self'
    '412/self', -- redefining argument 'self'
    '432/self', -- shadowing upvalue argument 'self'
}

files['locales/*'] = {
    ignore = {
        '631',
    },
}

globals = {
    string = {
        fields = {
            'join',
            'split',
            'trim',
        },
    },
    table = {
        fields = {
            'removemulti',
            'wipe',
        },
    },

    -- AddOn
    'FREE_ADB',
    'DBM',
    'BigWigsAPI',
    'BigWigsLoader',

    -- Constants
    'SOUNDKIT',
    'ALTERNATE_POWER_INDEX',
    'PLAYER_OFFLINE',
    'DEAD',
    'YOU',
    'THREAT_TOOLTIP',
    'LE_PARTY_CATEGORY_HOME',
    'LE_PARTY_CATEGORY_INSTANCE',

    -- FrameXML
    'CastingBarFrame',
    'CastingBarFrame_OnLoad',
    'CastingBarFrame_SetUnit',
    'ComboFrame',
    'CreateColor',
    'Enum',
    'FocusFrame',
    'MonkStaggerBar',
    'NamePlateDriverFrame',
    'PetCastingBarFrame',
    'PetCastingBarFrame_OnLoad',
    'PetFrame',
    'PlayerFrame',
    'PlayerPowerBarAlt',
    'TargetFrame',
    'TargetFrameToT',
    'TargetofFocusFrame',
    'TotemFrame',
    'UIParent',
    'GameTooltip',
    'GameTooltip_SetDefaultAnchor',
    'UnitFrame_OnEnter',
    'UnitFrame_OnLeave',
    'CompactRaidFrameManager',
    'CompactRaidFrameManager_SetSetting',
    'WeeklyRewardsFrame',

    -- namespaces
    'C_IncomingSummon',
    'C_NamePlate',
    'C_PvP',
    'C_ChallengeMode',
    'C_ChatInfo',
    'C_EncounterJournal',
    'C_WeeklyRewards',
    'C_PlayerInfo',
    'C_CVar',
    'C_BattleNet',
    'C_Map',

    -- API
    'CopyTable',
    'CreateFrame',
    'GetAddOnMetadata',
    'GetArenaOpponentSpec',
    'GetNetStats',
    'GetNumArenaOpponentSpecs',
    'GetPartyAssignment',
    'GetRaidTargetIndex',
    'GetReadyCheckStatus',
    'GetRuneCooldown',
    'GetSpecialization',
    'GetSpecializationInfoByID',
    'GetSpellPowerCost',
    'GetTexCoordsForRoleSmallCircle',
    'GetThreatStatusColor',
    'GetTime',
    'GetTotemInfo',
    'GetUnitChargedPowerPoints',
    'GetUnitPowerBarInfo',
    'GetUnitPowerBarInfoByID',
    'GetUnitPowerBarStringsByID',
    'InCombatLockdown',
    'IsLoggedIn',
    'IsPlayerSpell',
    'IsResting',
    'PartyUtil',
    'PlayerVehicleHasComboPoints',
    'PowerBarColor',
    'RegisterAttributeDriver',
    'RegisterStateDriver',
    'RegisterUnitWatch',
    'SecureButton_GetModifiedUnit',
    'SecureButton_GetUnit',
    'SecureHandlerSetFrameRef',
    'SetCVar',
    'SetPortraitTexture',
    'SetRaidTargetIconTexture',
    'ShowBossFrameWhenUninteractable',
    'UnitAffectingCombat',
    'UnitAura',
    'UnitCastingInfo',
    'UnitChannelInfo',
    'UnitClass',
    'UnitExists',
    'UnitFactionGroup',
    'UnitGUID',
    'UnitGetIncomingHeals',
    'UnitGetTotalAbsorbs',
    'UnitGetTotalHealAbsorbs',
    'UnitGroupRolesAssigned',
    'UnitHasIncomingResurrection',
    'UnitHasVehiclePlayerFrameUI',
    'UnitHasVehicleUI',
    'UnitHealth',
    'UnitHealthMax',
    'UnitHonorLevel',
    'UnitInParty',
    'UnitInRaid',
    'UnitInRange',
    'UnitIsConnected',
    'UnitIsGroupAssistant',
    'UnitIsGroupLeader',
    'UnitIsMercenary',
    'UnitIsPVP',
    'UnitIsPVPFreeForAll',
    'UnitIsPlayer',
    'UnitIsQuestBoss',
    'UnitIsTapDenied',
    'UnitIsUnit',
    'UnitIsVisible',
    'UnitPhaseReason',
    'UnitPlayerControlled',
    'UnitPower',
    'UnitPowerBarID',
    'UnitPowerDisplayMod',
    'UnitPowerMax',
    'UnitPowerType',
    'UnitPvpClassification',
    'UnitRace',
    'UnitReaction',
    'UnitSelectionType',
    'UnitStagger',
    'UnitThreatSituation',
    'UnitWatchRegistered',
    'UnregisterUnitWatch',
    'GetBuildInfo',
    'GetRealmName',
    'UnitClass',
    'UnitName',
    'UnitFactionGroup',
    'GetPhysicalScreenSize',
    'GetSpecializationInfo',
    'IsInGroup',
    'IsInRaid',
    'UnitIsDead',
    'UnitIsGhost',
    'IsUsableSpell',
    'CombatLogGetCurrentEventInfo',
    'CancelUnitBuff',
    'SpellIsPriorityAura',
    'SpellGetVisibilityInfo',
    'SpellIsSelfBuff',
    'UnitInVehicle',
    'tContains',
    'GetSpellInfo',
    'EJ_GetInstanceInfo',
    'UnitLevel',
    'UnitClassification',
    'GetCVar',
    'hooksecurefunc',
    'GetNumGroupMembers',
    'GetNumSubgroupMembers',
    'IsInInstance',
    'issecure',
    'GetSpellTexture',
    'UnitNameplateShowsWidgetsOnly',
    'UnitCanAttack',
    'GetSpellCooldown',
    'UnitIsDeadOrGhost',
    'GetLocale',
    'UnitIsEnemy',
    'UnitIsFriend',
    'PlaySound',
    'GetInstanceInfo',
    'UnitIsCharmed',
    'GetMouseFocus',
    'UnitCanAssist',
    'IsSpellKnown',
    'IsSpellInRange',
    'IsAddOnLoaded',
    'GetItemCount',
    'GetItemIcon',
    'GetItemCooldown',
    'IsEquippedItem',
    'GetZonePVPInfo',
    'GetWeaponEnchantInfo',
    'UnitBuff',
    'GetQuestItemInfo',
    'GetQuestCurrencyInfo',
    'GetQuestCurrencyID',
    'GetNumRewardSpells',
    'GetItemInfo',
    'Mixin',
    'nop',

    -- other
    'oUF_Player',
    'oUF_Pet',
    'oUF_Target',
    'oUF_TargetTarget',
    'oUF_Focus',
    'oUF_FocusTarget',
}
