local _G = getfenv(0)
local unpack = _G.unpack
local select = _G.select

local _, C = unpack(select(2, ...))

C.CharacterSettings = {
    ShadowLands = false,
    InstallationComplete = false,
    UIAnchor = {},
    UIAnchorTemp = {},
    SpellBinding = {},
    TalentManager = {},
    General = {
        HideTalkingHead = true,
        HideBossBanner = false,
        HideBossEmote = true,
        SimplifyErrors = true,
        EnhancedFriendsList = true,
        EnhancedMailButton = true,
        EnhancedDressup = true,
        OrderHallIcon = true,
        TradeTabs = true,
        PetFilter = true,
        MawThreatBar = true,
        EnhancedMenu = true,
        NakedButton = true,
        MissingStats = true,
        ItemLevel = true,
        GemEnchant = true,
        AzeriteTrait = true,
        AutoScreenshot = true,
        EarnedNewAchievement = true,
        ChallengeModeCompleted = true,
        PlayerLevelUp = false,
        PlayerDead = false,
        FasterZooming = true,
        ActionCamera = false,
        CursorTrail = true,
        Vignette = true,
        VignetteAlpha = .85,
        FasterLoot = false,
        FasterMovieSkip = true,
        ScreenSaver = true,
        ProposalTimer = true,
        GroupTool = true,
        RuneCheck = false,
        Countdown = '10',
        SaveRecipient = true,
        RecipientName = ''
    },
    Combat = {
        Enable = true,
        CombatAlert = true,
        AlertScale = .4,
        AlertSpeed = 1,
        SoundAlert = true,
            Interrupt = true,
            Dispel = true,
            SpellSteal = true,
            SpellMiss = true,
            LowHealth = true,
            LowHealthThreshold = .3,
            LowMana = true,
            LowManaThreshold = .3,
        PvPSound = true,
        SmartTab = true,
        EasyMark = true,
            EasyMarkKey = 1,
        EasyFocus = true,
            EasyFocusKey = 3,
            EasyFocusOnUnitframe = false,
        SimpleFloatingCombatText = true,
            Pet = true,
            Periodic = true,
            Merge = true,
            Incoming = true,
            Outgoing = false,
    },
    Announcement = {
        Enable = true,
        Channel = 4,
        PersonalMajorSpell = true,
        Interrupt = true,
        Dispel = true,
        Stolen = true,
        Reflect = true,
        BattleRez = true,
        Death = true,
        Feast = true,
        Cauldron = true,
        Soulwell = true,
        RefreshmentTable = true,
        RitualofSummoning = true,
        Bot = true,
        Codex = true,
        Mailbox = true,
        Portal = true,
        Toy = true,
        Quest = false,
        Reset = true
    },
    Aura = {
        Enable = true,
        Margin = 6,
        Offset = 12,
        BuffSize = 40,
        BuffPerRow = 12,
        BuffReverse = true,
        DebuffSize = 50,
        DebuffPerRow = 12,
        DebuffReverse = true,
        Reminder = true
    },
    Inventory = {
        Enable = true,
        Scale = 1,
        Offset = 26,
        Spacing = 3,
        SlotSize = 44,
        BagColumns = 14,
        BankColumns = 14,
        SortMode = 2,
        ItemLevel = true,
        MinItemLevelToShow = 1,
        NewItemFlash = true,
        BindType = true,
        CombineFreeSlots = true,
        SplitCount = 1,
        AutoDeposit = false,
        SpecialBagsColor = true,
        FavItemsList = {},
        ItemFilter = true,
        FilterEquipSet = true,
        FilterTradeGoods = true,
        FilterQuestItem = true,
        FilterJunk = true,
        FilterAzeriteArmor = true,
        FilterEquipment = true,
        FilterConsumable = true,
        FilterLegendary = true,
        FilterCollection = true,
        FilterFavourite = true,
        FilterAnima = true,
        AutoSellJunk = true,
        AutoRepair = true
    },
    Unitframe = {
        Enable = true,
        ColorStyle = 2,
        HealthColor = {r = .81, g = .81, b = .81},
        Transparent = true,
        Fader = true,
        MinAlpha = 0,
        MaxAlpha = 1,
        OutDuration = .3,
        InDuration = .3,
        InPvP = true,
        InInstance = true,
        MouseOver = false,
        InCombat = true,
        Targeting = true,
        Casting = true,
        Injured = true,
        ManaNotFull = false,
        HavePower = false,
        RangeCheck = true,
        RangeCheckAlpha = .4,
        Portrait = true,
        PowerBarHeight = 2,
        AlternativePowerBarHeight = 2,
        GCDIndicator = true,
        RaidTargetIndicator = true,
        RaidTargetIndicatorAlpha = .6,
        RaidTargetIndicatorSize = 16,
        CombatIndicator = true,
        RestingIndicator = true,
        HidePlayerTags = true,
        ClassPowerBar = true,
        ClassPowerBarHeight = 2,
        RunesTimer = false,
        StaggerBar = true,
        TotemsBar = true,
        TotemsBarHeight = 2,
        OnlyShowPlayer = true,
        AbbreviatedName = false,
        Castbar = true,
        CompactCastbar = true,
        CastingColor = {r = .31, g = .48, b = .85},
        UninterruptibleColor = {r = .66, g = .65, b = .65},
        CompleteColor = {r = .25, g = .63, b = .49},
        FailColor = {r = .73, g = .39, b = .43},
        SpellName = false,
        SpellTime = false,
        PlayerCastbarWidth = 200,
        PlayerCastbarHeight = 16,
        TargetCastbarWidth = 160,
        TargetCastbarHeight = 10,
        FocusCastbarWidth = 200,
        FocusCastbarHeight = 16,
        PlayerWidth = 160,
        PlayerHeight = 6,
        PetWidth = 60,
        PetHeight = 6,
        PetAurasPerRow = 3,
        TargetWidth = 160,
        TargetHeight = 6,
        TargetAurasPerRow = 6,
        ToTWidth = 60,
        ToTHeight = 6,
        FocusWidth = 60,
        FocusHeight = 6,
        FocusAurasPerRow = 3,
        ToFWidth = 60,
        ToFHeight = 6,
        Group = true,
        GroupShowName = false,
        ShowSolo = false,
        SmartRaid = true,
        ShowRaidBuff = false,
        DispellableOnly = false,
        RaidBuffSize = 8,
        ShowRaidDebuff = false,
        RaidDebuffSize = 12,
        GroupColorStyle = 2,
        GroupFilter = 6,
        PositionBySpec = false,
        ClickToCast = true,
        DebuffHighlight = true,
        CornerIndicator = true,
        CornerIndicatorScale = 1,
        InstanceAuras = true,
        RaidDebuffsScale = 1,
        AurasClickThrough = true,
        PartyWatcher = true,
        PartyWatcherSync = false,
        ThreatIndicator = true,
        PartyWidth = 62,
        PartyHeight = 28,
        PartyGap = 6,
        PartyHorizon = false,
        PartyReverse = false,
        RaidWidth = 38,
        RaidHeight = 30,
        RaidGap = 5,
        RaidHorizon = false,
        RaidReverse = true,
        Boss = true,
        BossWidth = 120,
        BossHeight = 18,
        BossGap = 60,
        BossAurasPerRow = 6,
        Arena = true,
        ArenaWidth = 120,
        ArenaHeight = 18,
        ArenaGap = 60,
        ArenaAurasPerRow = 6
    },
    Nameplate = {
        Enable = true,
        Width = 100,
        Height = 8,
        ControlCVars = true,
        NameOnly = true,
        TargetIndicator = true,
        TargetIndicatorColor = {r = .73, g = .92, b = .99},
        ThreatIndicator = true,
        ClassifyIndicator = true,
        QuestIndicator = true,
        ExecuteIndicator = false,
        ExecuteRatio = 0,
        SpitefulIndicator = true,
        ExplosiveIndicator = true,
        ExplosiveScale = 1.5,
        RaidTargetIndicator = true,
        RaidTargetIndicatorSize = 24,
        RaidTargetIndicatorAlpha = .6,
        FriendlyClassColor = false,
        HostileClassColor = true,
        TankMode = false,
        RevertThreat = false,
        SecureColor = {r = 1, g = 0, b = 1},
        TransColor = {r = 1, g = .8, b = 0},
        InsecureColor = {r = 1, g = 0, b = 0},
        OffTankColor = {r = .2, g = .7, b = .5},
        ColoredTarget = false,
        TargetColor = {r = 0, g = .6, b = 1},
        ColoredFocus = true,
        FocusColor = {r = 1, g = 1, b = 1},
        CustomUnitColor = true,
        CustomColor = {r = .8, g = .42, b = .31},
        CustomUnitList = '',
        ShowPowerList = '',
        ShowAura = true,
        AuraFilterMode = 3,
        AuraPerRow = 6,
        AuraSize = 22,
        AuraNumTotal = 6,
        TotemIcon = true,
        CastbarCompact = true,
        CastbarSpellName = false,
        CastbarSpellTime = false,
        MajorSpellsGlow = true,
        SpellTarget = true,
        InsideView = true,
        MinScale = .7,
        TargetScale = 1,
        MinAlpha = .6,
        OccludedAlpha = .2,
        VerticalSpacing = 1.8,
        HorizontalSpacing = 1.4
    },
    Tooltip = {
        Enable = true,
        BackdropAlpha = .65,
        FollowCursor = false,
        DisableFading = true,
        HideTitle = true,
        HideRealm = true,
        HideGuildRank = true,
        HideInCombat = false,
        BorderColor = true,
        SpecIlvl = true,
        SpecIlvlByAlt = true,
        Icon = true,
        TargetBy = true,
        ExtraInfo = true,
        HealthValue = false,
        PvEStats = true,
        MountSource = true,
    },
    Map = {
        Enable = true,
        WorldMapScale = 1,
        MaxWorldMapScale = 1,
        RemoveFog = true,
        Coords = true,
        MinimapScale = 1,
        WhoPings = true,
        ExpBar = true
    },
    Infobar = {
        Enable = true,
        AnchorTop = true,
        Height = 14,
        Mouseover = true,
        Stats = true,
        Spec = true,
        Durability = true,
        Guild = true,
        Friends = true,
        Report = true,
        Currencies = true,
        Gold = true
    },
    Notification = {
        Enable = true,
        BagFull = true,
        NewMail = true,
        LowDurability = true,
        RareFound = true,
        ParagonChest = true
    },
    Chat = {
        Enable = true,
        LockPosition = true,
        Width = 300,
        Height = 100,
        FadeOut = true,
        TimeVisible = 120,
        FadeDuration = 6,
        ShortenChannelName = true,
        CopyButton = true,
        VoiceButton = true,
        EasyChannelSwitch = true,
        SmartChatBubble = false,
        ChannelBar = true,
        WhisperInvite = false,
        InviteKeyword = '111 inv',
        GuildOnly = true,
        WhisperSticky = true,
        WhisperSound = true,
        SoundThreshold = 60,
        ExtendItemLink = true,
        LootIcon = true,
        DamageMeterFilter = true,
        SpamFilter = true,
        Matches = 1,
        BlockSpammer = false,
        BlockStrangerWhisper = false,
        BlockAddonSpam = true,
        GroupLootFilter = true,
        GroupLootThreshold = 2,
        GroupRoleIcon = true,
        DisableProfanityFilter = true
    },
    Actionbar = {
        Enable = true,
        Scale = 1,
        ButtonSize = 26,
        Hotkey = true,
        MacroName = true,
        CountNumber = true,
        ClassColor = false,
        EquipColor = true,
        ButtonFlash = true,
        Layout = 4, -- 1*12 2*12 3*12 2*18
        Bar4 = false,
        Bar5 = false,
        PetBar = true,
        StanceBar = false,
        VehicleBar = true,
        DynamicFade = true,
        FadeOutAlpha = 0,
        FadeInAlpha = 1,
        FadeOutDuration = 1,
        FadeInDuration = .3,
        ConditionCombat = true,
        ConditionTarget = false,
        ConditionDungeon = true,
        ConditionPvP = true,
        ConditionVehicle = true,
        CustomBar = false,
        CBMargin = 3,
        CBPadding = 3,
        CBButtonSize = 34,
        CBButtonNumber = 12,
        CBButtonPerRow = 6,
        CooldownNotify = true,
        CooldownPulse = true,
        CooldownDesaturate = true,
        BindType = 1
    },
    Cooldown = {
        Enable = true,
        Decimal = true,
        OverrideWA = false
    },
    Quest = {
        Automation = false,
        CompleteSound = true
    }
}

C.AccountSettings = {
    DetectVersion = C.AddonVersion,
    VersionCheck = true,
    UIScale = 1,
    HelpTips = {},
    GoldStatistic = {},
    ShadowOutline = true,
    BackdropColor = {r = .1, g = .1, b = .1},
    BackdropAlpha = .75,
    BorderColor = {r = .24, g = .24, b = .24},
    ButtonBackdropColor = {r = .05, g = .05, b = .05},
    ButtonBackdropAlpha = .25,
    GuildSortBy = 1,
    GuildSortOrder = true,
    GradientStyle = true,
    ReskinBlizz = true,
    ReskinAddons = true,
    TextureStyle = 1,
    NumberFormat = 1,
    FontOutline = false,
    WorldTextScale = 1,
    FloatingCombatText = true,
    FloatingCombatTextOldStyle = true,
    ChatFilterBlackList = '',
    ChatFilterWhiteList = '',
    CustomJunkList = {},
    NPAuraFilter = {[1] = {}, [2] = {}},
    RaidDebuffsList = {},
    RaidAuraWatch = {},
    NPMajorSpells = {},
    CornerSpellsList = {},
    PartySpellsList = {},
    AnnounceableSpellsList = {},
    KeystoneInfo = {},
    ProfileIndex = {},
    ProfileNames = {},
    UseCustomClassColor = true,
    CustomClassColors = {
        HUNTER = {b = 0.196078431372549, colorStr = 'ff009332', g = 0.580392156862745, r = 0},
        WARRIOR = {b = 0.4588235294117647, colorStr = 'ff9a8675', g = 0.5254901960784314, r = 0.6039215686274509},
        SHAMAN = {b = 0.4, colorStr = 'ff006166', g = 0.3843137254901961, r = 0},
        MAGE = {b = 0.8588235294117647, colorStr = 'ff3498db', g = 0.596078431372549, r = 0.203921568627451},
        PRIEST = {b = 0.8862745098039215, colorStr = 'ffd2dae2', g = 0.8549019607843137, r = 0.8235294117647058},
        DEATHKNIGHT = {b = 0.2509803921568627, colorStr = 'ffb71540', g = 0.08235294117647059, r = 0.7176470588235294},
        WARLOCK = {b = 1, colorStr = 'ff9c88ff', g = 0.5333333333333333, r = 0.611764705882353},
        DEMONHUNTER = {b = 0.8784313725490196, colorStr = 'fff368e0', g = 0.407843137254902, r = 0.9529411764705882},
        ROGUE = {b = 0.192156862745098, colorStr = 'fffbc530', g = 0.7725490196078432, r = 0.984313725490196},
        DRUID = {b = 0.1333333333333333, colorStr = 'ffe67e22', g = 0.4941176470588236, r = 0.9019607843137255},
        MONK = {b = 0.6980392156862745, colorStr = 'ff33d9b2', g = 0.8509803921568627, r = 0.2},
        PALADIN = {b = 0.4588235294117647, colorStr = 'ffff7675', g = 0.4627450980392157, r = 1}
    },
    ColorPickerPlus = {}
}
