local _, ns = ...

if ns.locale ~= "zhCN" and ns.locale ~= "zhTW" then return end

ns.localization.profile = "角色单独配置"
ns.localization.profileTooltip = "在角色单独配置和公共配置之间切换。"
ns.localization.credits = "致谢"
ns.localization.install = "安装"
ns.localization.needReload = "重载界面来应用改动。"
ns.localization.needReloadPopup = "你需要重载界面来使改动生效。\n\n现在就重载界面么？"
ns.localization.requiresReload = "这个选项需要重载界面来生效。"
ns.localization.reload = "重载界面"
ns.localization.resetData = "移除数据"
ns.localization.resetDataTooltip = "移除所有已保存的数据，例如你的角色共有多少金币。"
ns.localization.resetOptions = "移除已保存的数据"
ns.localization.resetOptionsTooltip = "移除所有已保存的数据，重置为默认值。"
ns.localization.resetCharBox = "移除这个角色已保存的数据："
ns.localization.layoutText = "使用下面的按钮来转换到其他界面布局。\n你也可以使用命令行'/freeui dps' 或者 '/freeui heal'"
ns.localization.notificationPreviewText = "这是一个通知示例。"
ns.localization.notificationPreviewCallbackText = "大多数通知都有相关的点击动作。"
ns.localization.author = "FreeUI by Haleth on wowinterface.com"
ns.localization.authorSubText = "Lightsword @ Argent Dawn - EU"
ns.localization.NEW = "NEW!"

ns.localization.general = "综合"
ns.localization.generalSubText = "这些选项控制这个界面的大部分通用设置。"
ns.localization.generalFeatures = "特性"
ns.localization.generalMisc = "杂项"
ns.localization.generalbuffreminder = "Buff 缺失提醒"
ns.localization.generalbuffreminderTooltip = "战斗中提示缺失的重要Buff"
ns.localization.generalbuffTracker = "Buff 触发监控"
ns.localization.generalbuffTrackerTooltip = "在屏幕中下的位置显示对应职业的重要触发。"
ns.localization.generalcombatText = "战斗文字"
ns.localization.generalcombatTextTooltip = "显示伤害和治疗数字。"
ns.localization.generalhelmcloakbuttons = "头盔/披风显示按钮"
ns.localization.generalhelmcloakbuttonsTooltip = "使你可以在角色面板显示或隐藏头盔/披风。"
ns.localization.generalinterrupt = "打断提示"
ns.localization.generalinterruptTooltip = "在特定场合和情况下通告打断"
ns.localization.generalinterrupt_party = "小队"
ns.localization.generalinterrupt_partyTooltip = "启用打断通告当你在5人小队和场景战役时（场景战役只有在勾选了副本选项时才会生效）。"
ns.localization.generalinterrupt_bgs = "战场"
ns.localization.generalinterrupt_bgsTooltip = "启用打断通告当你在战场时。"
ns.localization.generalinterrupt_lfg = "副本"
ns.localization.generalinterrupt_lfgTooltip = "启用打断通告当你在副本队伍时。"
ns.localization.generalinterrupt_outdoors = "野外"
ns.localization.generalinterrupt_outdoorsTooltip = "启用打断通告当你不在任何副本时。"
ns.localization.generalmailButton = "邮件一键收取"
ns.localization.generalmailButtonTooltip = "在邮件界面添加一个按钮来一键收取所有邮件。"
ns.localization.generalnameplates = "姓名板"
ns.localization.generalnameplatesTooltip = "美化默认姓名板外观。禁用这个选项如果你想使用另外的姓名板插件。"
ns.localization.generalrareAlert = "稀有通知"
ns.localization.generalrareAlertTooltip = "当在潘达利亚发现稀有时显示一个提醒，小地图上有具体位置。"
ns.localization.generalrareAlert_playSound = "播放声音"
ns.localization.generalthreatMeter = "仇恨值"
ns.localization.generalthreatMeterTooltip = "在目标框体上添加一个仇恨计量条，当你是坦克时显示第二仇恨的名字和仇恨量，当你是输出时显示你和坦克的仇恨对比。"
ns.localization.generaluiScaleAuto = "强制优化界面缩放"
ns.localization.generaluiScaleAutoTooltip = "自动为你的分辨率使用最优化的界面缩放。"
ns.localization.generalundressButton = "脱衣按钮"
ns.localization.generalundressButtonTooltip = "在试衣间界面添加一键脱光按钮"

ns.localization.appearance = "外观"
ns.localization.appearanceSubText = "改变部分外观"
ns.localization.appearanceColours = "颜色"
ns.localization.appearanceFonts = "字体"
ns.localization.appearancecolourScheme = "颜色方案"
ns.localization.appearancecolourScheme1 = "职业染色"
ns.localization.appearancecolourScheme2 = "自定义"
ns.localization.appearancecolourScheme1Tooltip = "自动根据你的职业来染色。"
ns.localization.appearancecolourScheme2Tooltip = "选择自定义颜色"
ns.localization.appearancechooseColour = "选择..."
ns.localization.appearancefontUseAlternativeFont = "使用备选字体"
ns.localization.appearancefontUseAlternativeFontTooltip = "使用聊天框的字体来替换界面默认的像素字体。"
ns.localization.appearancefontSizeNormal = "普通字体"
ns.localization.appearancefontSizeLarge = "大号字体"
ns.localization.appearancefontOutline = "字体描边"
ns.localization.appearancefontOutlineStyle = "描边"
ns.localization.appearancefontOutlineStyle1 = "普通"
ns.localization.appearancefontOutlineStyle2 = "单色"
ns.localization.appearancefontOutlineStyle1Tooltip = "搭配普通字体使用（非像素型字体）"
ns.localization.appearancefontOutlineStyle2Tooltip = "搭配像素字体使用"
ns.localization.appearancefontShadow = "阴影"
ns.localization.appearancesampleText = "示例文字"

ns.localization.automation = "便利功能"
ns.localization.automationSubText = "这些设置帮助你自动执行一些常用动作"
ns.localization.automationautoAccept = "自动接受好友或公会成员的组队邀请"
ns.localization.automationautoRepair = "自动修理"
ns.localization.automationautoRepair_guild = "优先使用公会修理"
ns.localization.automationautoRoll = "自动选择分解或贪婪装绑的绿装"
ns.localization.automationautoRoll_maxLevel = "仅在满级时生效"
ns.localization.automationautoSell = "自动售卖垃圾"
ns.localization.automationautoSellTooltip = "自动售卖货色品质物品，除非它属于自定义套装"
ns.localization.automationquestRewardHighlight = "任务奖励高亮"
ns.localization.automationquestRewardHighlightTooltip = "交任务时高亮最贵的奖励"
ns.localization.automationautoSetRole = "跳过不必要的职责确认"
ns.localization.automationautoSetRoleTooltip = "当你已经选择职责，或为纯DPS职业时跳过职责确认"
ns.localization.automationautoSetRole_useSpec = "依据当前天赋确定职责"
ns.localization.automationautoSetRole_useSpecTooltip = "总是依据你的当前天赋确定职责，不再提示职责确认窗口"
ns.localization.automationautoSetRole_verbose = "通告模式"
ns.localization.automationautoSetRole_verboseTooltip = "当跳过职责确认时发出通告"

ns.localization.actionbars = "动作条"
ns.localization.actionbarsSubText = "动作条以及按钮设置"
ns.localization.actionbarsenable = "启用"
ns.localization.actionbarsenableTooltip = "禁用这个选项如果你想使用默认动作条"
ns.localization.actionbarsenableStyle = "启用动作条样式"
ns.localization.actionbarsenableStyleTooltip = "使用其他动作条插件时禁用此项以保证兼容"
ns.localization.actionbarshotkey = "显示快捷键绑定"
ns.localization.actionbarsrightbars_mouseover = "鼠标滑过显示右侧动作条"

ns.localization.bags = "背包"
ns.localization.bagsSubText = "选择设置你喜欢的样式"
ns.localization.bagsGeneral = "通用设置"
ns.localization.bagsStyleSpecific = "样式"
ns.localization.bagssize = "背包大小"
ns.localization.bagsstyle = "背包样式"
ns.localization.bagsstyle1 = "所有背包合一"
ns.localization.bagsstyle2 = "美化默认背包"
ns.localization.bagsstyle3 = "禁用"
ns.localization.bagsslotsShowAlways = "显示物品格子"
ns.localization.bagsslotsShowAlwaysTooltip = "启用这个选项来显示背包格子"
ns.localization.bagshideSlots = "隐藏背包条"
ns.localization.bagshideSlotsTooltip = "禁用这个选项当你想添加移除背包时"

ns.localization.menubar = "菜单条"
ns.localization.menubarSubText = "信息条位于屏幕底部的面板，移动鼠标显示额外的功能和信息"
ns.localization.menubarenable = "启用"
ns.localization.menubarenableButtons = "启用按钮"
ns.localization.menubarenableButtonsTooltip = "在菜单条上显示按钮"
ns.localization.menubarbuttons_mouseover = "鼠标滑过显示按钮"
ns.localization.menubarbuttons_mouseoverTooltip = "只在鼠标滑过时显示按钮"

ns.localization.notifications = "通知功能"
ns.localization.notificationsSubText = "设置通知功能"
ns.localization.notificationsWhen = "通知时机"
ns.localization.notificationsHow = "通知方式"
ns.localization.notificationsPreview = "预览"
ns.localization.notificationsenable = "启用"
ns.localization.notificationsenableTooltip = "允许显示通知栏将会在界面上方显示通知条，通过鼠标任何按键点击均可以隐藏。左键点击它可激活某些动作，如显示日历。"
ns.localization.notificationsplaySounds = "声音提示"
ns.localization.notificationsplaySoundsTooltip = "当出现通知时播放声音提示"
ns.localization.notificationsanimations = "显示动画"
ns.localization.notificationsanimationsTooltip = "动画显示/隐藏通知条"
ns.localization.notificationstimeShown = "持续时间"
ns.localization.notificationscheckEvents = "日历事件"
ns.localization.notificationscheckEventsTooltip = "当你有待定的日历事件时显示通知"
ns.localization.notificationscheckGuildEvents = "公会事件"
ns.localization.notificationscheckGuildEventsTooltip = "当你有待定的公会事件时显示通知.这类行事历不在默认日历上显示，很容易被忽视"
ns.localization.notificationscheckMail = "邮件"
ns.localization.notificationscheckMailTooltip = "当有新邮件时显示通知"
ns.localization.notificationscheckBagsFull = "背包满"
ns.localization.notificationscheckBagsFullTooltip = "当背包慢时显示通知"

ns.localization.unitframes = "头像框体"
ns.localization.unitframesSubText = "These options control most of the options for the unit frames. If you want to move the unit frames easily, install oUF_MovableFrames."
ns.localization.unitframesenable = "启用"
ns.localization.unitframesenableTooltip = "如果你想使用其他头像插件则禁用这个选项"
ns.localization.unitframesautoPosition = "自动布局"
ns.localization.unitframesautoPositionTooltip = "根据屏幕分辨率自动设置头像框体位置，如需手动配置则禁用此项"
ns.localization.unitframesenableGroup = "小队/团队框体"
ns.localization.unitframesenableGroupTooltip = "如果你想使用其他团队框架类插件则禁用这个选项"
ns.localization.unitframeslimitRaidSize = "限制团队框体大小"
ns.localization.unitframeslimitRaidSizeTooltip = "勾选此项团队框体将最多显示25人"
ns.localization.unitframespartyNameAlways = "显示团员名字"
ns.localization.unitframespartyNameAlwaysTooltip = "勾选此项在DPS/TANK模式下显示团员名字"
ns.localization.unitframescastbarSeparate = "分离显示玩家施法条"
ns.localization.unitframescastbarSeparateTooltip = "禁用此项将在玩家头像框体内显示施法条"
ns.localization.unitframescastbarSeparateOnlyCasters = "仅对法系职业生效"
ns.localization.unitframescastbarSeparateOnlyCastersTooltip = "勾选此项将只对术士法师牧师启用独立施法条"
ns.localization.unitframesabsorb = "吸收量"
ns.localization.unitframesabsorbTooltip = "在框体上显示吸收量"
ns.localization.unitframestargettarget = "目标的目标"
ns.localization.unitframestargettargetTooltip = "显示目标的目标框体"
ns.localization.unitframeshealerClasscolours = "总是使用职业染色"
ns.localization.unitframeshealerClasscoloursTooltip = "启用职业染色来代替治疗模式下的透明渐变"
ns.localization.unitframespvp = "PVP 图标"
ns.localization.unitframespvpTooltip = "在玩家框体显示一个红色的PVP图标"

ns.localization.unitframesstatusIndicator = "状态指示"
ns.localization.unitframesstatusIndicatorTooltip = "在玩家框体显示休息或战斗状态"
ns.localization.unitframesstatusIndicatorCombat = "战斗状态"
ns.localization.unitframesstatusIndicatorCombatTooltip = "在玩家框体显示战斗状态。如果禁用，则只显示休息状态"

ns.localization.unitframesenableArena = "竞技场/扛旗者框体"
ns.localization.unitframesenableArenaTooltip = "打开竞技场敌对目标和战场扛旗者的框体。"

ns.localization.tooltip = "鼠标提示"
ns.localization.tooltipSubText = "调整鼠标信息的外观和功能。"
ns.localization.tooltipanchorCursor = "跟随鼠标"
ns.localization.tooltipguildrank = "公会阶级"
ns.localization.tooltiptitle = "玩家头衔"

ns.localization.classmod = "职业特定"
ns.localization.classmodSubText = "设置加载职业特定的组件"

local classes = UnitSex("player") == 2 and LOCALIZED_CLASS_NAMES_MALE or LOCALIZED_CLASS_NAMES_FEMALE

for class, localized in pairs(classes) do
	ns.localization["classmod"..strlower(class)] = localized
end

ns.localization.classmoddeathknight = ns.localization.classmoddeathknight..":|cffffffff 死骑符文条"
ns.localization.classmoddruidMana = ns.localization.classmoddruid..":|cffffffff 德鲁伊变形法力条"
ns.localization.classmoddruidEclipse = ns.localization.classmoddruid..":|cffffffff 鸟德月蚀条"
ns.localization.classmodmage = ns.localization.classmodmage..":|cffffffff 法师资源监视"
ns.localization.classmodmonk = ns.localization.classmodmonk..":|cffffffff 武僧真气条"
ns.localization.classmodpaladinHP = ns.localization.classmodpaladin..":|cffffffff 圣骑豆子监视"
ns.localization.classmodpaladinRF = ns.localization.classmodpaladin..":|cffffffff 防骑正义之怒提示"
ns.localization.classmodpriest = ns.localization.classmodpriest..":|cffffffff 牧师宝珠条"
ns.localization.classmodwarlock = ns.localization.classmodwarlock..":|cffffffff 术士资源条"

ns.localization.credits = "Credits"
ns.localization.thankYou = "Thank you:"
ns.localization.alza = "For AlzaUI, which once formed the basis for FreeUI"
ns.localization.haste = "For the oUF framework, the foundation of the unit frames in this UI"
ns.localization.tukz = "For allowing the use of his code, and collaboration in UI development"
ns.localization.zork = "For rActionBarStyler, rActionButtonStyler, and rBuffFrameStyler"
ns.localization.others = "as well as..."