local _, ns = ...

if ns.locale ~= "zhCN" and ns.locale ~= "zhTW" then return end

ns.localization.profile = "角色单独配置"
ns.localization.profileTooltip = "在角色单独配置和公共配置之间切换。"
ns.localization.credits = "致谢"
ns.localization.install = "安装"
ns.localization.needReload = "|cffff2735重载界面来应用改动。|r"
ns.localization.needReloadPopup = "需要重载界面来使改动生效。\n\n现在就重载界面么？"
ns.localization.requiresReload = "这个选项需要重载界面来生效。"
ns.localization.reload = "重载界面"
ns.localization.reset = "移除数据"
ns.localization.resetTooltip = "移除所有已保存的数据，重置为默认值。"

ns.localization.layoutText = "使用下面的按钮来转换到其他界面布局。\n你也可以使用命令行 '|cffff2735/freeui dps|r' 或者 '|cff3a9d36/freeui healer|r'"
ns.localization.notificationPreviewText = "这是一个通知示例。"
ns.localization.notificationPreviewCallbackText = "大多数通知都有相关的点击动作。"
ns.localization.author = "FreeUI by Haleth on wowinterface.com"
ns.localization.authorSubText = "Lightsword @ Argent Dawn - EU"
ns.localization.NEW = "NEW!"

ns.localization.general = "综合"
ns.localization.generalSubText = "这些选项控制这个界面的大部分通用设置"
ns.localization.generalmisc = "通用设置"
ns.localization.generalcooldown = "冷却相关"
ns.localization.generalcamera = "视角镜头"
ns.localization.generaluiscaleset = "界面缩放"
ns.localization.generalhideTalkingHead = "隐藏情景对话框"
ns.localization.generalhideTalkingHeadTooltip = "隐藏情景对话框"
ns.localization.generalhideBossBanner = "隐藏副本掉落通知横幅"
ns.localization.generalhideBossBannerTooltip = "隐藏副本掉落通知横幅"
ns.localization.generalflashCursor = "鼠标闪光"
ns.localization.generalflashCursorTooltip = "鼠标移动时添加一道闪光轨迹"
ns.localization.generalmailButton = "邮件一键收取"
ns.localization.generalmailButtonTooltip = "在邮件界面添加一个按钮来一键收取所有邮件"
ns.localization.generalalreadyKnown = "配方/坐骑/宠物染色"
ns.localization.generalalreadyKnownTooltip = "在商人/拍卖行界面给已经学会的配方/坐骑/宠物染色"
ns.localization.generalmissingStats = "属性补全"
ns.localization.generalmissingStatsTooltip = "在人物面板显示所有的属性"
ns.localization.generalfasterLoot = "快速拾取"
ns.localization.generalfasterLootTooltip = "快速拾取"
ns.localization.generalraidManager = "团队工具"
ns.localization.generalraidManagerTooltip = "在队伍中时启用团队工具条"
ns.localization.generalquickMarking = "快速设置标记"
ns.localization.generalquickMarkingTooltip = "Alt+鼠标左键点击人物模型可以快速设置标记"
ns.localization.generalquickFocusing = "快速设置焦点"
ns.localization.generalquickFocusingTooltip = "shift+鼠标左键点击人物模型或框体可以快速设为焦点\n重复点击空白处则清除焦点"
ns.localization.generalprogressBar = "经验声望荣誉进度条"
ns.localization.generalprogressBarTooltip = "在小地图下方添加一个经验声望荣誉进度条"
ns.localization.generalPVPSound = "击杀音效"
ns.localization.generalPVPSoundTooltip = "为PVP行为添加类似DotA的击杀/连杀音效"
ns.localization.generalclickCast = "点击施法"
ns.localization.generalclickCastTooltip = "启用团队框体点击施法，打开技能面板设定具体配置"
ns.localization.generalclickCast_filter = "框体过滤"
ns.localization.generalclickCast_filterTooltip = "过滤玩家自己和目标的框体"
ns.localization.generalcooldownCount = "冷却计时"
ns.localization.generalcooldownCountTooltip = "取代暴雪自带的冷却计时"
ns.localization.generalcooldownCount_decimal = "冷却时间低于5秒时显示毫秒"
ns.localization.generalcooldownCount_decimalTooltip = "冷却时间低于5秒时显示毫秒"
ns.localization.generalcooldownPulse = "冷却完成提示"
ns.localization.generalcooldownPulseTooltip = "当技能或物品完成冷却后在屏幕中央显示一个图标提示"
ns.localization.generalcameraIncrement = "镜头调整速度"
ns.localization.generaluiScaleAuto = "强制界面缩放"
ns.localization.generaluiScaleAutoTooltip = "自动为当前分辨率使用最合适的界面缩放值"
ns.localization.generaluiScale = "自定义缩放"



ns.localization.appearance = "外观"
ns.localization.appearanceSubText = "控制界面外观相关的设置"
ns.localization.appearancetheme = "全局"
ns.localization.appearanceskin = "细节"
ns.localization.appearanceColours = "颜色"


ns.localization.appearancefontStyle = "字体调整"
ns.localization.appearancefontStyleTooltip = "调整界面字体的大小和颜色"
ns.localization.appearanceenableTheme = "全局主题"
ns.localization.appearanceenableThemeTooltip = "启用黑色半透明的全局主题"
ns.localization.appearanceaddons = "插件"
ns.localization.appearanceobjectiveTracker = "任务追踪"
ns.localization.appearanceobjectiveTrackerTooltip = "美化增强任务追踪栏"
ns.localization.appearancepetBattle = "宠物对战"
ns.localization.appearancepetBattleTooltip = "美化增强宠物对战界面"
ns.localization.appearancevignette = "边缘阴影"
ns.localization.appearancevignetteTooltip = "在屏幕边缘添加一层阴影制造类似景深的效果"
ns.localization.appearancevignetteAlpha = "调整阴影强度"
ns.localization.appearanceDBM = "DBM"
ns.localization.appearanceBW = "BigWigs"
ns.localization.appearanceWA = "WeakAuras"
ns.localization.appearancePGF = "Skada"
ns.localization.appearanceSKADA = "PremadeGroupsFilter"

--ns.localization.appearanceFonts = "字体"
ns.localization.appearancecolourScheme = "颜色方案"
ns.localization.appearancecolourScheme1 = "职业染色"
ns.localization.appearancecolourScheme2 = "自定义"
ns.localization.appearancecolourScheme1Tooltip = "自动根据你的职业来染色。"
ns.localization.appearancecolourScheme2Tooltip = "选择自定义颜色"
ns.localization.appearancechooseColour = "选择..."
--ns.localization.appearancefontUseAlternativeFont = "使用备选字体"
--ns.localization.appearancefontUseAlternativeFontTooltip = "使用聊天框的字体来替换界面默认的像素字体。"
--ns.localization.appearancefontUseChinesePixelFont = "使用中文点阵字体"
--ns.localization.appearancefontUseChinesePixelFontTooltip = "使用中文点阵字体来替换界面默认的像素字体。"
--ns.localization.appearancefontSizeNormal = "普通字体"
--ns.localization.appearancefontSizeLarge = "大号字体"
--ns.localization.appearancefontOutline = "字体描边"
--ns.localization.appearancefontOutlineStyle = "描边"
--ns.localization.appearancefontOutlineStyle1 = "普通"
--ns.localization.appearancefontOutlineStyle2 = "单色"
--ns.localization.appearancefontOutlineStyle1Tooltip = "搭配普通字体使用（非像素型字体）"
--ns.localization.appearancefontOutlineStyle2Tooltip = "搭配像素字体使用"
--ns.localization.appearancefontShadow = "阴影"
--ns.localization.appearancesampleText = "sample SAMPLE 示例文字"

ns.localization.automation = "便利功能"
ns.localization.automationSubText = "这些设置帮助玩家自动执行一些常用动作"
ns.localization.automationautoSellJunk = "售卖垃圾"
ns.localization.automationautoSellJunkTooltip = "打开商人窗口时自动售卖灰色品质物品"
ns.localization.automationautoScreenShot = "截图"
ns.localization.automationautoScreenShotTooltip = "获得成就时自动截图"
ns.localization.automationautoSetRole = "职责确认"
ns.localization.automationautoSetRoleTooltip = "当你已经选择职责或为纯DPS职业时跳过职责确认"
ns.localization.automationautoRepair = "修理"
ns.localization.automationautoRepairTooltip = "打开商人窗口时自动修理装备"
ns.localization.automationautoActionCam = "动态镜头"
ns.localization.automationautoActionCamTooltip = "自动启用动态镜头"
ns.localization.automationautoQuest = "任务交接"
ns.localization.automationautoQuestTooltip = "自动交接任务"
ns.localization.automationautoBuyStack = "杂货购买"
ns.localization.automationautoBuyStackTooltip = "按住shift自动购买整组"
ns.localization.automationautoTabBinder = "Tab绑定"
ns.localization.automationautoTabBinderTooltip = "战场/竞技场中自动切换tab为选择敌对玩家忽略宠物"
ns.localization.automationautoAcceptInvite = "接受组队邀请"
ns.localization.automationautoAcceptInviteTooltip = "自动接受来自公会或好友的组队邀请"
ns.localization.automationautoInvite = "自动邀请"
ns.localization.automationautoInviteTooltip = "自动邀请使用关键字密语的玩家\n输入 /ainv 关键字"



ns.localization.actionbars = "动作条"
ns.localization.actionbarsSubText = "动作条以及按钮设置"
ns.localization.actionbarsenable = "启用动作条布局"
ns.localization.actionbarsenableTooltip = "禁用这个选项如果你想使用默认动作条"
ns.localization.actionbarsenableStyle = "启用动作条样式"
ns.localization.actionbarsenableStyleTooltip = "使用其他动作条插件时禁用此项以保证兼容"
ns.localization.actionbarshotKey = "显示快捷键绑定"
ns.localization.actionbarsmacroName = "显示宏名称"
ns.localization.actionbarsrightbars_mouseover = "鼠标悬停显示右侧动作条"
ns.localization.actionbarsstancebar_mouseover = "鼠标悬停显示姿态条"
ns.localization.actionbarspetbar_mouseover = "鼠标悬停显示宠物动作条"



ns.localization.inventory = "背包"
ns.localization.inventorySubText = "选择设置你喜欢的样式"
ns.localization.inventoryGeneral = "通用设置"
ns.localization.inventoryStyle = "样式"
ns.localization.inventoryuseCategory = "背包根据物品分类"
ns.localization.inventoryreverseSort = "反向整理背包物品"
ns.localization.inventoryenable = "启用背包"
ns.localization.inventorygearSetFilter = "装备方案里的装备作为单独的分类"
ns.localization.inventoryitemLevel = "显示装备等级"
ns.localization.inventorynewitemFlash = "新获得物品闪光"
ns.localization.inventoryitemSlotSize = '背包格子大小'



ns.localization.infobar = "信息条"
ns.localization.infobarSubText = "信息条位于屏幕顶部，移动鼠标显示额外的功能和信息"
ns.localization.infobarenable = "启用"
ns.localization.infobarmouseover = "鼠标滑过显示按钮"
ns.localization.infobarmouseoverTooltip = "只在鼠标滑过时显示按钮"

ns.localization.infobarstats = "时间/帧数/延迟"
ns.localization.infobarstatsTooltip = "显示时间/帧数/延迟等信息"
ns.localization.infobarmicroMenu = "游戏菜单"

ns.localization.infobarskadaTool = "Skada助手"
ns.localization.infobarskadaToolTooltip = "左键显示Skada窗口\n右键隐藏Skada窗口\n中键清除Skada数据"
ns.localization.infobarspecTalent = "天赋/专精"
ns.localization.infobarspecTalentTooltip = "显示天赋专精\n左键切换专精\n右键切换拾取专精"
ns.localization.infobarfriends = "好友"
ns.localization.infobarfriendsTooltip = "显示好友在线信息"
ns.localization.infobarcurrencies = "货币"
ns.localization.infobarcurrenciesTooltip = "显示各类货币以及统计"
ns.localization.infobarreport = "日常/周常信息"
ns.localization.infobarreportTooltip = "显示日常/周常/副本进度/突袭等信息"



ns.localization.notification = "通知功能"
ns.localization.notificationSubText = "设置通知功能"
ns.localization.notificationWhen = "通知时机"
ns.localization.notificationHow = "通知方式"
ns.localization.notificationPreview = "预览"
ns.localization.notificationenable = "启用"
ns.localization.notificationenableTooltip = "允许显示通知栏将会在界面上方显示通知条，通过鼠标任何按键点击均可以隐藏。左键点击它可激活某些动作，如显示日历。"
ns.localization.notificationplaySounds = "声音提示"
ns.localization.notificationplaySoundsTooltip = "当出现通知时播放声音提示"
ns.localization.notificationanimations = "显示动画"
ns.localization.notificationanimationsTooltip = "动画显示/隐藏通知条"
ns.localization.notificationtimeShown = "持续时间"
ns.localization.notificationcheckEvents = "日历事件"
ns.localization.notificationcheckEventsTooltip = "当你有待定的日历事件时显示通知"
ns.localization.notificationcheckGuildEvents = "公会事件"
ns.localization.notificationcheckGuildEventsTooltip = "当你有待定的公会事件时显示通知.这类行事历不在默认日历上显示，很容易被忽视"
ns.localization.notificationcheckMail = "邮件"
ns.localization.notificationcheckMailTooltip = "当有新邮件时显示通知"
ns.localization.notificationcheckBagsFull = "背包满"
ns.localization.notificationcheckBagsFullTooltip = "当背包慢时显示通知"

ns.localization.unitframes = "头像框体"
ns.localization.unitframesSubText = "These options control most of the options for the unit frames."
ns.localization.unitframesenable = "启用头像框体"
ns.localization.unitframesenableTooltip = "如果你想使用其他头像插件则禁用这个选项。"
ns.localization.unitframesgradient = "渐变磨砂"
ns.localization.unitframesgradientTooltip = "头像框体使用渐变磨砂外观。"
ns.localization.unitframesdarkBorder = "环绕阴影"
ns.localization.unitframesdarkBorderTooltip = "头像框体外圈环绕阴影。"
ns.localization.unitframesportrait = "动态肖像"
ns.localization.unitframesportraitTooltip = "头像框体使用动态肖像。"

ns.localization.unitframespowerTypeColor = "能量条类型染色"
ns.localization.unitframespowerTypeColorTooltip = "玩家自己的能量条根据能量类型染色。"
ns.localization.unitframeshealthClassColor = "损血职业染色"
ns.localization.unitframeshealthClassColorTooltip = "透明模式下损失血量按照职业染色，禁用则总是红色。"

ns.localization.unitframescastbar = "启用施法条"
ns.localization.unitframescastbarTooltip = "禁用此项如果你想使用其他施法条类的插件。"
ns.localization.unitframescastbarSeparate = "玩家施法条分离"
ns.localization.unitframescastbarSeparateTooltip = "禁用此项则玩家的施法条合并在头像框上。"
ns.localization.unitframesabsorb = "吸收量"
ns.localization.unitframesabsorbTooltip = "在头像框体上发亮提示吸收量。"

ns.localization.unitframesenableGroup = "启用小队/团队框体"
ns.localization.unitframesenableGroupTooltip = "使用其他团队框架类插件前先禁用这个选项。"
ns.localization.unitframesshowRaidFrames = "显示小队/团队框架"
ns.localization.unitframesshowRaidFramesTooltip = "禁用此项则隐藏小队/团队框架，即使你已经在一个队伍/团队当中。"
ns.localization.unitframeslimitRaidSize = "团队显示人数限制"
ns.localization.unitframeslimitRaidSizeTooltip = "启用后只显示5个队伍/25个队员框体，多出的则隐藏。"
ns.localization.unitframespartyNameAlways = "队员名字"
ns.localization.unitframespartyNameAlwaysTooltip = "在团队框架上显示队员名字。"
ns.localization.unitframespartyMissingHealth = "损失血量"
ns.localization.unitframespartyMissingHealthTooltip = "在团队框架上显示具体损失血量数字。"

ns.localization.unitframestransMode = "透明模式"
ns.localization.unitframestransModeTooltip = "禁用此项则使用传统职业染色模式。"
ns.localization.unitframespvp = "PVP 指示"
ns.localization.unitframespvpTooltip = "在玩家框体上显示一个红色的 P 表示处于 PVP 状态。"

ns.localization.unitframesstatusIndicator = "状态指示"
ns.localization.unitframesstatusIndicatorTooltip = "在玩家框体显示休息或战斗状态"
ns.localization.unitframesstatusIndicatorCombat = "战斗状态"
ns.localization.unitframesstatusIndicatorCombatTooltip = "在玩家框体显示战斗状态。如果禁用，则只显示休息状态"

ns.localization.unitframesenableArena = "启用 PVP 框体"
ns.localization.unitframesenableArenaTooltip = "PVP 环境下的特殊框体，竞技场框体，战场中携带旗帜和宝珠人员的框体。"

ns.localization.quests = "任务追踪"
ns.localization.questsSubText = "All options related to quests and the objective tracker."
ns.localization.questsquestRewardHighlight = "Quest reward highlighting"
ns.localization.questsquestRewardHighlightTooltip = "When turning in a quest, highlight the quest reward with the highest vendor sell price."
ns.localization.questsrememberObjectiveTrackerState = "Save objective tracker expanded/collapsed state"
ns.localization.questsrememberObjectiveTrackerStateTooltip = "Collapses the objective tracker when you log in if it was collapsed when you logged out. Works on a per-character basis."
ns.localization.questsalwaysCollapseObjectiveTracker = "Always collapse objective tracker on login"
ns.localization.questsquestObjectiveTrackerStyle = "任务追踪栏样式"
ns.localization.questsquestObjectiveTrackerStyleTooltip = "启用任务追踪栏的样式。\n如果要使用其他任务追踪类插件请先禁用这个选项。"


ns.localization.tooltip = "鼠标提示"
ns.localization.tooltipSubText = "调整鼠标提示的外观和功能"
ns.localization.tooltipenable = "启用鼠标提示强化"
ns.localization.tooltipenableTooltip = "禁用这个选项如果你想使用其他鼠标提示类插件"
ns.localization.tooltipcursor = "跟随鼠标"
ns.localization.tooltipcursorTooltip = "鼠标提示的位置跟随鼠标，禁用则固定在屏幕右下角"
ns.localization.tooltiphidePVP = "隐藏 PVP 状态"
ns.localization.tooltiphideFaction = "隐藏阵营"
ns.localization.tooltiphideTitle = "隐藏头衔"
ns.localization.tooltiphideRealm = "隐藏服务器"
ns.localization.tooltiphideRank = "隐藏公会会阶"
ns.localization.tooltipcombatHide = "战斗中隐藏鼠标提示"
ns.localization.tooltipborderColor = "鼠标提示的边框按照物品品质染色"
ns.localization.tooltiptipIcon = "显示物品图标"
ns.localization.tooltiptipClear = "清理无用信息"
ns.localization.tooltipilvlSpec = "显示装等和专精"
ns.localization.tooltiplinkHover = "鼠标悬停聊天框链接时显示鼠标提示"
ns.localization.tooltipextraInfo = "显示额外的信息"
ns.localization.tooltipazeriteTrait = "整理艾泽里特护甲特质的信息"




ns.localization.classmod = "职业特定"
ns.localization.classmodSubText = "设置加载职业特定的组件"

local classes = UnitSex("player") == 2 and LOCALIZED_CLASS_NAMES_MALE or LOCALIZED_CLASS_NAMES_FEMALE

for class, localized in pairs(classes) do
	ns.localization["classmod"..strlower(class)] = localized
end

ns.localization.classmodclassResource = "|cffffffff 特殊资源"
ns.localization.classmodclassResourceTooltip = "显示特定职业专精的特殊资源\n例如术士碎片惩戒骑圣能\n禁用此项如果你想使用其他提供类似功能的插件。"

ns.localization.credits = "Credits"
ns.localization.thankYou = "Thank you:"
ns.localization.alza = "For AlzaUI, which once formed the basis for FreeUI"
ns.localization.haste = "For the oUF framework, the foundation of the unit frames in this UI"
ns.localization.tukz = "For allowing the use of his code, and collaboration in UI development"
ns.localization.zork = "For rActionBarStyler, rActionButtonStyler, and rBuffFrameStyler"
ns.localization.others = "as well as..."
