local _, ns = ...




ns.localization.credits = "Credits"
ns.localization.reset = "Reset"
ns.localization.install = "Installer"
ns.localization.profile = "Character-specific settings"
ns.localization.profileTooltip = "Switch between a profile that applies to all characters and one that is unique to this character."
ns.localization.resetCheck = "Remove all saved options, and reset them to their default values."
ns.localization.needReload = "|cffff2735You need to reload the UI to apply your changes.|r"
ns.localization.reloadCheck = "|cffff2735You need to reload the UI to apply your changes.\n\nWould you like to do so now?|r"


ns.localization.author = "FreeUI Continued by Solor"
ns.localization.authorSubText = "https://github.com/Solor/FreeUI"
ns.localization.haleth = "Haleth"
ns.localization.halethSubText = "For the original version of FreeUI"
ns.localization.alza = "Alza"
ns.localization.alzaSubText = "For AlzaUI, which once formed the basis for FreeUI"
ns.localization.haste = "Haste"
ns.localization.hasteSubText = "For the oUF framework, the foundation of the unit frames in this UI"
ns.localization.tukz = "Tukz"
ns.localization.tukzSubText = "For allowing the use of his code, and collaboration in UI development"
ns.localization.zork = "Zork"
ns.localization.zorkSubText = "For rActionBarStyler, rActionButtonStyler, and rBuffFrameStyler"
ns.localization.siweia = "siweia"
ns.localization.siweiaSubText = "For NDUI, which I stole a lot of codes from"
ns.localization.others = "as well as..."
ns.localization.othersSubText_1 = "Allez, AlleyKat, Caellian, p3lim, Shantalya, tekkub, Tuller, Wildbreath"
ns.localization.othersSubText_2 = "Shestak, aliluya555, Paojy, Rubgrsch"


ns.localization.general = "General"
ns.localization.general_subText = "These options control most of the common settings in the UI."
ns.localization.general_subCategory_basic = "Basic"
ns.localization.general_hideTalkingHead = "Hide talking head"
ns.localization.general_hideTalkingHead_tooltip = "Hide NPC talking head."
ns.localization.general_hideBossBanner = "Hide boss banner"
ns.localization.general_hideBossBanner_tooltip = "Hide Boss banner."
ns.localization.general_colletMail = "Easy mail"
ns.localization.general_colletMail_tooltip = "Adds a button to the mail frame to collect all mail attachments with one click."
ns.localization.general_alreadyKnown = "Already known"
ns.localization.general_alreadyKnown_tooltip = "Colorizes recipes/mounts/pets/toys that is already known."
ns.localization.general_fullStats = "Missing stats"
ns.localization.general_fullStats_tooltip = "Character frame full stats."
ns.localization.general_missingBuffs = "Missing buffs"
ns.localization.general_missingBuffs_tooltip = "Buffs Reminder (shout/intellect/poison)."
ns.localization.general_fasterLoot = "Faster loot"
ns.localization.general_fasterLoot_tooltip = "Faster auto looting."
ns.localization.general_raidManager = "Group tool"
ns.localization.general_raidManager_tooltip = "Enable group tool."
ns.localization.general_progressBar = "Exp/rep/honer tracker"
ns.localization.general_progressBar_tooltip = "Tracker for exp/rep/honer."
ns.localization.general_itemLevel = "Item level"
ns.localization.general_itemLevel_tooltip = "Shows item level."
ns.localization.general_durability = "Durability"
ns.localization.general_durability_tooltip = "Shows gear durability."
ns.localization.general_subCategory_fct = "Combat"
ns.localization.general_combatText = "Float combat text"
ns.localization.general_combatText_tooltip = "Enable float combat text."
ns.localization.general_combatText_info = "Enter/leave combat"
ns.localization.general_combatText_info_tooltip = "Shows enter/leave combat info."
ns.localization.general_combatText_incoming = "Received damage"
ns.localization.general_combatText_outgoing = "Damage done"

ns.localization.general_PVPSound = "PVP sound"
ns.localization.general_PVPSound_tooltip = "Adds DotA like sound effect for PVP killing."
ns.localization.general_clickCast = "Click cast"
ns.localization.general_clickCast_tooltip = "Enable click cast."

ns.localization.general_marker = "Easy marking"
ns.localization.general_marker_tooltip = "Mark any unit by alt + left click."
ns.localization.general_focuser = "Easy focusing"
ns.localization.general_focuser_tooltip = "Focus any unit by shift + left click."
ns.localization.general_subCategory_cooldown = "Cooldown"
ns.localization.general_cooldown = "Cooldown count"
ns.localization.general_cooldown_decimal = "Decimal"
ns.localization.general_cooldown_decimalTooltip = "Decimal for cooldown count in 5s."
ns.localization.general_cooldownPulse = "Cooldown pulse"
ns.localization.general_cooldownPulse_tooltip = "Flashes the icon of the ability or item in the middle of screen whenever it finish cooldown."
ns.localization.general_actionCam = "ActionCam"
ns.localization.general_actionCam_tooltip = "Enable actioncam."
ns.localization.general_actionCam_full = "Fully actioncam"
ns.localization.general_actionCam_full_tooltip = "Enable fully actioncam."
ns.localization.general_subCategory_uiscale = "UI Scale"
ns.localization.general_uiScaleAuto = "Force optimal UI scale"
ns.localization.general_uiScaleAuto_tooltip = "Automatically apply the best UI scale for current resolution."
ns.localization.general_uiScale = "Customize UI scale"





ns.localization.appearance = "Appearance"
ns.localization.appearance_subText = "You can change the appearance of various aspects of the UI here."
ns.localization.appearance_subCategory_basic = "Basic"
ns.localization.appearance_themes = "Global theme"
ns.localization.appearance_themes_tooltip = "Enable global dark theme."
ns.localization.appearance_backdropAlpha = "theme opacity"

ns.localization.appearance_vignette = "Vignette"
ns.localization.appearance_vignette_tooltip = "Adds a shadow overlay to screen edge."
ns.localization.appearance_vignetteAlpha = "vignette opacity"

ns.localization.appearance_shadow = "Shadow border"
ns.localization.appearance_shadow_tooltip = "Adds smooth shadow border to most of UI elements."
ns.localization.appearance_gradient = "Gradient style"
ns.localization.appearance_gradient_tooltip = "Enable gradient style on buttons."
ns.localization.appearance_subCategory_misc = "Misc"
ns.localization.appearance_questTracker = "Objective tracker"
ns.localization.appearance_questTracker_tooltip = "Restyle objective tracker."
ns.localization.appearance_petBattle = "Pet battle"
ns.localization.appearance_petBattle_tooltip = "Restyle pet battle UI."
ns.localization.appearance_flashCursor = "Flash cursor"
ns.localization.appearance_flashCursor_tooltip = "Places a star at the cursor, with size proportional to the cursor speed."
ns.localization.appearance_subCategory_font = "Fonts"
ns.localization.appearance_fonts = "Adjust fonts"
ns.localization.appearance_fonts_tooltip = "Adjust the size of default fonts."
ns.localization.appearance_subCategory_addons = "AddOns"
ns.localization.appearance_DBM = "DBM"
ns.localization.appearance_DBM_tooltip = "Restyle DBM."
ns.localization.appearance_BigWigs = "BigWigs"
ns.localization.appearance_BigWigs_tooltip = "Restyle BigWigs."
ns.localization.appearance_WeakAuras = "WeakAuras"
ns.localization.appearance_WeakAuras_tooltip = "Restyle WeakAuras."
ns.localization.appearance_PremadeGroupsFilter = "Premade Groups Filter"
ns.localization.appearance_PremadeGroupsFilter_tooltip = "Restyle Premade Groups Filter."
ns.localization.appearance_Skada = "Skada"
ns.localization.appearance_Skada_tooltip = "Restyle Skada."




ns.localization.automation = "Automation"
ns.localization.automation_subText = "With these features, the UI can perform common tasks automatically."
ns.localization.automation_subCategory_automation = "Basic"
ns.localization.automation_autoSellJunk = "Sell junk"
ns.localization.automation_autoSellJunk_tooltip = "Automatically sell grey quality items to vendors, unless they are used in an equipment set."
ns.localization.automation_autoScreenShot = "Screenshot"
ns.localization.automation_autoScreenShot_tooltip = "Automatically takes a screenshot when you earn an achievement."
ns.localization.automation_autoSetRole = "Skip unnecessary role poll popups"
ns.localization.automation_autoSetRole_tooltip = "Skip the role poll popup if your role is already set or you are playing a pure dps class."
ns.localization.automationautoSetRole_useSpec = "Set role based on current specialization"
ns.localization.automationautoSetRole_useSpecTooltip = "Always attempt to set your role automatically based on your spec, never showing the popup."
ns.localization.automationautoSetRole_verbose = "Verbose mode"
ns.localization.automationautoSetRole_verboseTooltip = "Enable to be informed of what happens when the popup is skipped."
ns.localization.automation_autoRepair = "Repair"
ns.localization.automation_autoRepair_tooltip = "Automatically repair your gear."
ns.localization.automation_autoBuyStack = "Buy"
ns.localization.automation_autoBuyStack_tooltip = "Automatically buy a stack by alt + left click."
ns.localization.automation_autoQuest = "Quest"
ns.localization.automation_autoQuest_tooltip = "Automatically accept and deliver quests."
ns.localization.automation_autoTabBinder = "Tab bind"
ns.localization.automation_autoTabBinder_tooltip = "Automatically change your TAB key binding to only target enemy playerswhen in PvP zones, and to target all enemies when not."
ns.localization.automation_autoAcceptInvite = "Invite"
ns.localization.automation_autoAcceptInvite_tooltip = "Automatically accept invites from friends and guild members."
ns.localization.automation_autoInvite = "自动邀请"
ns.localization.automation_autoInvite_tooltip = "自动邀请使用关键字密语的玩家，默认关键字（invite）。\n/ainv 关键字 （更换关键字）\n/ainv off （禁用自动邀请）"






ns.localization.notification = "Notification"
ns.localization.notification_subText = "These options let you choose when and how the UI should show notifications."
ns.localization.notification_subCategory_banner = "Basic"
ns.localization.notification_enableBanner = "Notification banner"
ns.localization.notification_enableBanner_tooltip = "Allow notifications to be shown. A banner will appear at the top of the UI."
ns.localization.notification_playSounds = "Sound"
ns.localization.notification_playSounds_tooltip = "Plays a sound when a notification is shown."
ns.localization.notification_checkMail = "New mail"
ns.localization.notification_checkMail_tooltip = "Show a notification when you have new mail."
ns.localization.notification_checkBagsFull = "Bags full"
ns.localization.notification_checkBagsFull_tooltip = "Show a notification when your bags are full."
ns.localization.notification_autoRepairCost = "Repair cost"

ns.localization.notification_autoSellJunk = "Sell junk"

ns.localization.notification_subCategory_combat = "Combat"
ns.localization.notification_interrupt = "Interrupt"
ns.localization.notification_interrupt_tooltip = "Play a sound when you successfully interrupt."
ns.localization.notification_interruptAnnounce = "Announcement"
ns.localization.notification_interruptAnnounce_tooltip = "Announces when you successfully interrupt(only inside dungeons)."
ns.localization.notification_dispel = "Dispel"
ns.localization.notification_dispel_tooltip = "Play a sound when you successfully Dispel."
ns.localization.notification_dispelAnnounce = "Announcement"
ns.localization.notification_dispelAnnounce_tooltip = "Announces when you successfully Dispel(only inside dungeons)."
ns.localization.notification_vitalSpells = "Vital spell/event"
ns.localization.notification_vitalSpells_tooltip = "Announces some important spells(feast/portal/repairbot)."
ns.localization.notification_resurrect = "Resurrection"
ns.localization.notification_resurrect_tooltip = "Announces resurrect information."
ns.localization.notification_sapped = "Sap"
ns.localization.notification_sapped_tooltip = "Announces when a rogue saps you."
ns.localization.notification_emergency = "Emergency"
ns.localization.notification_emergency_tooltip = "Plays a sound alert when your health or mana reaches a critical level (health less than 50% or mana less than 30%)."
ns.localization.notification_lowHealth = "HP threshold"
ns.localization.notification_lowMana = "MP threshold"
ns.localization.notification_subCategory_rares = "Rare"
ns.localization.notification_rare = "Rare"
ns.localization.notification_rare_tooltip = "Shows a alert when a rare nearby."
ns.localization.notification_rareSound = "Sound"
ns.localization.notification_rareSound_tooltip = "Plays a sound when a rare nearby."
ns.localization.notification_subCategory_quest = "Quest"
ns.localization.notification_questNotifier = "Quest notifier"
ns.localization.notification_questProgress = "Quest progress"
ns.localization.notification_onlyCompleteRing = "Complete ring"


ns.localization.infobar = "Infobar"
ns.localization.infobar_subText = "The infobar is the panel at the top of the screen. \nMoving your mouse over it reveals additional functionality and information."
ns.localization.infobar_subCategory_cores = "Basic"
ns.localization.infobar_enable = "Enable"
ns.localization.infobar_mouseover = "Show blocks on mouseover"
ns.localization.infobar_mouseover_Tooltip = "Only show the blocks when moving the cursor over the menu bar."
ns.localization.infobar_stats = "Time/FPS/Latency"
ns.localization.infobar_statsTooltip = "Show time/FPS/latency informations."
ns.localization.infobar_microMenu = "Micro menu"
ns.localization.infobar_microMenu_Tooltip = "Show game menu."
ns.localization.infobar_skadaHelper = "Skada helper"
ns.localization.infobar_skadaHelper_Tooltip = "Left click to toggle Skada panel\nRight click to hide Skada panel\nMiddle click to reset Skada data."
ns.localization.infobar_specTalent = "Talent/Spec"
ns.localization.infobar_specTalent_Tooltip = "Show talent and specialization\nLeft click to change specialization\nRight click to change loot specialization."
ns.localization.infobar_friends = "Friends"
ns.localization.infobar_friends_Tooltip = "Show friends."
ns.localization.infobar_currencies = "Currencies"
ns.localization.infobar_currencies_Tooltip = "Show currencies and count."
ns.localization.infobar_report = "Daily/weekly"
ns.localization.infobar_report_Tooltip = "Show daily weekly informations."
ns.localization.infobar_durability = "Durability"
ns.localization.infobar_durability_Tooltip = "Show gears durability."







ns.localization.actionbar = "Actionbar"
ns.localization.actionbar_subText = "These options are specific to the action bars and their buttons."
ns.localization.actionbar_subCategory_layout = "Basic"

ns.localization.actionbar_enable = "Enable"
ns.localization.actionbar_enable_tooltip = "Uncheck if you want to use another action bars addon."
ns.localization.actionbar_layoutStyle = "Layout style"
ns.localization.actionbar_layoutStyle1 = "Default (3*12)"
ns.localization.actionbar_layoutStyle2 = "Divide bar3 on side (2*18)"
ns.localization.actionbar_layoutStyle3 = "Minimalist (hide all actionbars)"
ns.localization.actionbar_buttonSizeNormal = "Button size normal"
ns.localization.actionbar_buttonSizeNormal_Tooltip = "Button size for main bar."
ns.localization.actionbar_buttonSizeSmall = "Button size small"
ns.localization.actionbar_buttonSizeSmall_Tooltip = "Button size for side bar."
ns.localization.actionbar_buttonSizeBig = "Button size big"
ns.localization.actionbar_buttonSizeBig_Tooltip = "Button size for stance bar."
ns.localization.actionbar_buttonSizeHuge = "Button size huge"
ns.localization.actionbar_buttonSizeHuge_Tooltip = "Button size for extra bar."
ns.localization.actionbar_hotKey = "Show hotkey"
ns.localization.actionbar_macroName = "Show macro name"
ns.localization.actionbar_count = "Show item counts"
ns.localization.actionbar_classColor = "Class colour button border"
ns.localization.actionbar_senableStyle = "Button style"
ns.localization.actionbar_senableStyle_Tooltip = "You may need to disable this option to ensure compatibility with other action bars addons."
ns.localization.actionbar_hoverBind = "Hover bind"
ns.localization.actionbar_hoverBindTooltip = "Type /hb then bind buttons on mouseover."
ns.localization.actionbar_sideBar = "Side bar"
ns.localization.actionbar_sideBarTooltip = "Show side bar."
ns.localization.actionbar_sideBarMouseover = "Side bar mouseover"
ns.localization.actionbar_sideBarMouseover_Tooltip = "Show side bar on mouseover."
ns.localization.actionbar_petBar = "Pet bar"
ns.localization.actionbar_petBar_Tooltip = "Show pet bar."
ns.localization.actionbar_petBarMouseover = "Pet bar mouseover"
ns.localization.actionbar_petBarMouseover_Tooltip = "Show pet bar on mouseover."
ns.localization.actionbar_stanceBar = "Stance bar"
ns.localization.actionbar_stanceBar_Tooltip = "Show stance bar."
ns.localization.actionbar_stanceBarMouseover = "Stance bar mouseover"
ns.localization.actionbar_stanceBarMouseover_Tooltip = "Show stance bar on mouseover."
ns.localization.actionbar_bar3 = "Bar3"
ns.localization.actionbar_bar3_Tooltip = "Show bar3."
ns.localization.actionbar_bar3Mouseover = "Bar3 mouseover"
ns.localization.actionbar_bar3Mouseover_Tooltip = "Show bar3 on mouseover."
ns.localization.actionbar_subCategory_extra = "Extra"
ns.localization.actionbar_subCategory_bind = "Bind"
ns.localization.actionbar_subCategory_feature = "Misc"



ns.localization.inventory = "Inventory"
ns.localization.inventory_subText = "Choose and customize a bag style of your liking."
ns.localization.inventory_enable = "Enable"
ns.localization.inventory_enable_Tooltip = "Uncheck if you want to use another inventory addon."
ns.localization.inventory_itemLevel = "Show item level"
ns.localization.inventory_newitemFlash = "New item flash"
ns.localization.inventory_useCategory = "Sort items by type"
ns.localization.inventory_gearSetFilter = "Equipment set"
ns.localization.inventory_questItemFilter = "Quest related"
ns.localization.inventory_tradeGoodsFilter = "Trade goods"
ns.localization.inventory_mechagonItemFilter = "Mechagon stuffs"
ns.localization.inventory_reverseSort = "Reverse sort bags"
ns.localization.inventory_itemSlotSize = 'Slot size'
ns.localization.inventory_bagColumns = 'Columns'


ns.localization.tooltip = "Tooltip"
ns.localization.tooltip_subText = "Adjust the appearance and functionality of the game tooltip."
ns.localization.tooltip_enable = "Enable tooltip"
ns.localization.tooltip_enable_Tooltip = "Uncheck if you want to use another tooltip addon."
ns.localization.tooltip_cursor = "Keeps the tooltip near cursor"

ns.localization.tooltip_hideTitle = "Hide title"
ns.localization.tooltip_hideRealm = "Hide realm"
ns.localization.tooltip_hideRank = "Hide guild rank"
ns.localization.tooltip_combatHide = "Hide tooltip in combat"
ns.localization.tooltip_borderColor = "Coloured by item quality"
ns.localization.tooltip_tipIcon = "Icons"

ns.localization.tooltip_ilvlSpec = "Item level and spec"
ns.localization.tooltip_linkHover = "Chat frame link hover"
ns.localization.tooltip_extraInfo = "Extra info"
ns.localization.tooltip_azeriteTrait = "Azerite traits"




ns.localization.chat = "Chat"
ns.localization.chat_subText = "Adjust the appearance and functionality of the game chat."
ns.localization.chat_enable = "Enable"
ns.localization.chat_enable_Tooltip = "Uncheck if you want to use another chat addon."

ns.localization.chat_lockPosition = "Lock position"
ns.localization.chat_useOutline = "Outline"
ns.localization.chat_useOutline_Tooltip = "Add outline for chat text."
ns.localization.chat_whisperSound = "Whisper alert"
ns.localization.chat_whisperSound_Tooltip = "Add sound alert for whisper messages."
ns.localization.chat_timeStamp = "Time stamp"
ns.localization.chat_timeStamp_Tooltip = "Add customized time stamp."
ns.localization.chat_itemLink = "Item link"
ns.localization.chat_itemLink_Tooltip = "Expand item links in chat or when you or someone in your group receives loot to display item slot and item level."
ns.localization.chat_spamageMeter = "Spamage meter"
ns.localization.chat_spamageMeter_Tooltip = "Suppresses chat messages from damage meters."
ns.localization.chat_chatButton = "Chat button"
ns.localization.chat_channelSticky = "Channel sticky"
ns.localization.chat_lineFading = "Line fading"
ns.localization.chat_useFilter = "Chat filter"
ns.localization.chat_useFilter_Tooltip = "Enable chat filter."
ns.localization.chat_autoBubble = "Chat bubble"
ns.localization.chat_autoBubble_Tooltip = "Only enable chat bubble in raid."


ns.localization.chat = "Chat"
ns.localization.chat_subText = "Adjust the appearance and functionality of the game chat."
ns.localization.chat_subCategory_basic = "Basic"
ns.localization.chat_enable = "Enable"
ns.localization.chat_enable_tooltip = "Uncheck if you want to use another chat addon."
ns.localization.chat_lockPosition = "Lock position"
ns.localization.chat_fontOutline = "Font outline"
ns.localization.chat_whisperAlert = "Whisper alert"
ns.localization.chat_timeStamp = "time stamp"
ns.localization.chat_timeStampColor = "color"
ns.localization.chat_showItemLevel = "Item link"
ns.localization.chat_showItemLevel_tooltip = "Expand item links in chat or when you or someone in your group receives loot to display item slot and item level."
ns.localization.chat_spamageMeter = "Spamage meter"
ns.localization.chat_spamageMeter_tooltip = "Suppresses chat messages from damage meters."
ns.localization.chat_chatButton = "Copy button"
ns.localization.chat_fading = "Fading"
ns.localization.chat_filters = "Spam filter"
ns.localization.chat_autoBubble = "Bubble"




ns.localization.map = "Map"
ns.localization.map_subText = "Adjust the appearance and functionality of the game maps."
ns.localization.map_subCategory_worldMap = "World map"
ns.localization.map_coords = "Show coords"
ns.localization.map_coords_tooltip = "Show player and cursor coords on world map."
ns.localization.map_mapReveal = "Map reveal"
ns.localization.map_mapReveal_tooltip = "Reveals every portion of every zone of the world map."
ns.localization.map_subCategory_miniMap = "Minimap"
ns.localization.map_miniMap = "Minimap enhancement"
ns.localization.map_whoPings = "Show who pings"
ns.localization.map_miniMapSize = "Adjust minimap size"
ns.localization.map_microMenu = "Micro menu"
ns.localization.map_microMenu_tooltip = "Shows micro menu by mouse middle click."
ns.localization.map_marker = "World marker"
ns.localization.map_marker_tooltip = "Show world marker button when player in a group."
ns.localization.map_progressBar = "Progress bar"
ns.localization.map_progressBar_tooltip = "Adds a progress bar to tracker exp/rep/honer."




ns.localization.unitframe = "Unitframe"
ns.localization.unitframe_subText = "These options control most of the options for the unit frames."
ns.localization.unitframe_enable = "Enable Unit frames"
ns.localization.unitframe_enable_Tooltip = "Uncheck if you want to use another unit frames addon."
ns.localization.unitframe_line = ""
ns.localization.unitframe_transMode = "Transparency"
ns.localization.unitframe_transMode_Tooltip = "Uncheck if you prefer traditional solid colour mode."
ns.localization.unitframe_colourSmooth = "Colour smooth"
ns.localization.unitframe_colourSmooth_Tooltip = "Color player/target/focus health with a smooth gradient based on the current health percentage."

ns.localization.unitframe_portrait = "Portrait"
ns.localization.unitframe_portrait_Tooltip = "Add portrait on unitframes."
ns.localization.unitframe_healer_layout = "Healer layout"
ns.localization.unitframe_healer_layout_Tooltip = "Symmetrical layout, more friendly for healers."
ns.localization.unitframe_frameVisibility = "Minimalist mode"
ns.localization.unitframe_frameVisibility_Tooltip = "Only show unitframes when player enter combat or have a target."
ns.localization.unitframe_threat = "Threat"
ns.localization.unitframe_threat_Tooltip = "Show threat indicator."
ns.localization.unitframe_rangeCheck = "Range fade"
ns.localization.unitframe_rangeCheck_Tooltip = "Changes the opacity of a unit frame based on whether the frame's unit is in the player's range."
ns.localization.unitframe_overAbsorb = "Absorb"
ns.localization.unitframe_overAbsorb_Tooltip = "Show damage absorb shield."
ns.localization.unitframe_healPrediction = "Heal prediction"
ns.localization.unitframe_healPrediction_Tooltip = "Show incoming heals."
ns.localization.unitframe_dispellable = "Dispelable"
ns.localization.unitframe_dispellable_Tooltip = "Highlighting debuffs that are dispellable by the player."
ns.localization.unitframe_enableCastbar = "Castbar"
ns.localization.unitframe_enableCastbar_Tooltip = "Uncheck if you want to use another castbar addon."
ns.localization.unitframe_castbar_separatePlayer = "Separate player castbar"
ns.localization.unitframe_castbar_separateTarget = "Separate target castbar"
ns.localization.unitframe_enableGroup = "Enable Party/Raid frames"
ns.localization.unitframe_enableGroup_Tooltip = "Uncheck if you want to use another addon for party and raid frames."
ns.localization.unitframe_groupNames = "Show names"
ns.localization.unitframe_groupNames_Tooltip = "Show group member names."
ns.localization.unitframe_groupColourSmooth = "Colour smooth"
ns.localization.unitframe_groupColourSmooth_Tooltip = "Color party/raid health with a smooth gradient based on the current health percentage."
ns.localization.unitframe_bossColourSmooth = "Colour smooth"
ns.localization.unitframe_bossColourSmooth_Tooltip = "Color boss health with a smooth gradient based on the current health percentage."
ns.localization.unitframe_enableBoss = "Boss frames"
ns.localization.unitframe_enableBoss_Tooltip = "Enables boss frames, uncheck if you want to use another addon for boss frames."
ns.localization.unitframe_enableArena = "Arena frames"
ns.localization.unitframe_enableArena_Tooltip = "Enables arena frames, uncheck if you want to use another addon for arena frames."
ns.localization.unitframe_debuffbyPlayer = "Aura filter"
ns.localization.unitframe_debuffbyPlayer_Tooltip = "Only show debuffs that casted by player on target unitframe."
ns.localization.unitframe_quakeTimer = "Quake timer"
ns.localization.unitframe_quakeTimer_Tooltip = "Show quake timer bar."
ns.localization.unitframe_classPower = "Class power"
ns.localization.unitframe_classPower_Tooltip = "Show player's class resources (like Chi Orbs or Holy Power) and combo points."
ns.localization.unitframe_stagger = "Stagger"
ns.localization.unitframe_stagger_Tooltip = "Show brewmaster stagger."
ns.localization.unitframe_totems = "Totems"
ns.localization.unitframe_totems_Tooltip = "Show shaman totem indicator."
ns.localization.unitframe_groupFilter = "Groups to show"




ns.localization.classmod = "Class specific"
ns.localization.classmodSubText = "These options allow you to toggle the class-specific modules in the UI."

local classes = UnitSex("player") == 2 and LOCALIZED_CLASS_NAMES_MALE or LOCALIZED_CLASS_NAMES_FEMALE

for class, localized in pairs(classes) do
	ns.localization["classmod"..strlower(class)] = localized
end

ns.localization.classmodhavocFury = "|cffffffff Demon Hunter havoc fury"
ns.localization.classmodhavocFuryTooltip = "Change fury colour based on current value."


