local _, ns = ...

ns.localization.profile = "Character-specific settings"
ns.localization.profileTooltip = "Switch between a profile that applies to all characters and one that is unique to this character."
ns.localization.reset = "Reset"
ns.localization.resetCheck = "Remove all saved options, and reset them to their default values."
ns.localization.install = "Installer"
ns.localization.needReload = "|cffff2735You need to reload the UI to apply your changes.|r"
ns.localization.needReloadPopup = "You need to reload the UI to apply your changes.\n\nWould you like to do so now?"
ns.localization.requiresReload = "Changing this option requires a UI reload."
ns.localization.reload = "Reload UI"
ns.localization.resetData = "Remove data"
ns.localization.resetDataTooltip = "Check to remove all saved data, such as how much money your characters have and click cast settings."
ns.localization.resetOptions = "Remove saved options"
ns.localization.resetOptionsTooltip = "Check to remove all saved options, and reset them to their default values."
ns.localization.author = "|cff808080<|rFree|cff9c84efUI|r|cff808080>|r by |cffe8155cHaleth|r and |cff37b1d6Solor|r"
ns.localization.authorSubText = "|cff808080https://github.com/Solor/FreeUI|r"




ns.localization.general = "General"
ns.localization.generalSubText = "These options control most of the common settings in the UI."
ns.localization.generalmisc = "Misc"
ns.localization.generalcooldown = "Cooldown"
ns.localization.generalcamera = "Camera"
ns.localization.generaluiscaleset = "UI Scale"
ns.localization.generalhideTalkingHead = "Hide talking head"
ns.localization.generalhideTalkingHeadTooltip = "Hide NPC talkinghead."
ns.localization.generalhideBossBanner = "Hide boss banner"
ns.localization.generalhideBossBannerTooltip = "Hide Boss banner."
ns.localization.generalflashCursor = "Flash cursor"
ns.localization.generalflashCursorTooltip = "Places a star at the cursor, with size proportional to the cursor speed."
ns.localization.generalmailButton = "Mail collection button"
ns.localization.generalmailButtonTooltip = "Adds a button to the mail frame to collect all mail attachments with one click."
ns.localization.generalalreadyKnown = "Already known"
ns.localization.generalalreadyKnownTooltip = "Colorizes recipes/mounts/pets/toys that is already known."
ns.localization.generalmissingStats = "Missing stats"
ns.localization.generalmissingStatsTooltip = "Character frame full stats."
ns.localization.generalmissingBuffs = "Missing buffs"
ns.localization.generalmissingBuffsTooltip = "Buffs Reminder (shout/intellect/poison)."
ns.localization.generalfasterLoot = "Faster loot"
ns.localization.generalfasterLootTooltip = "Faster auto looting."
ns.localization.generalraidManager = "Raid manager"
ns.localization.generalraidManagerTooltip = "Enable raid manager."
ns.localization.generalquickMarking = "Easy mark"
ns.localization.generalquickMarkingTooltip = "Easy marking by alt + left click."
ns.localization.generalquickFocusing = "Easy focus"
ns.localization.generalquickFocusingTooltip = "Easy focusing by shift + left click."
ns.localization.generalprogressBar = "Exp/rep/honer tracker"
ns.localization.generalprogressBarTooltip = "Tracker for exp/rep/honer (below minimap)."
ns.localization.generalPVPSound = "PVP sound"
ns.localization.generalPVPSoundTooltip = "DotA like sound effect for PVP killing."
ns.localization.generalclickCast = "Click cast"
ns.localization.generalclickCastTooltip = "Click cast for party/raid frames."
ns.localization.generalclickCast_filter = "Click cast filter"
ns.localization.generalclickCast_filterTooltip = "Ignore click cast for player/target frames."
ns.localization.generalcooldownCount = "Cooldown count"
ns.localization.generalcooldownCountTooltip = "Show cooldown timer."
ns.localization.generalcooldownCount_decimal = "Decimal count"
ns.localization.generalcooldownCount_decimalTooltip = "Decimal for cooldown count in 5s."
ns.localization.generalcooldownPulse = "Cooldown pulse"
ns.localization.generalcooldownPulseTooltip = "Flashes the icon of the ability or item in the middle of screen whenever it finish cooldown."
ns.localization.generalcameraIncrement = "Camera zoom speed"
ns.localization.generaluiScaleAuto = "Force optimal UI scale"
ns.localization.generaluiScaleAutoTooltip = "Automatically apply the best UI scale for current resolution."
ns.localization.generaluiScale = "Customize UI scale"





ns.localization.appearance = "Appearance"
ns.localization.appearanceSubText = "You can change the appearance of various aspects of the UI here."
ns.localization.appearanceline_1 = ""
ns.localization.appearanceline_2 = ""
ns.localization.appearanceline_3 = ""
ns.localization.appearanceline_4 = ""
ns.localization.appearanceaddShadowBorder = "Shadow"
ns.localization.appearanceaddShadowBorderTooltip = "Add smooth shadow border to most of UI elements."
ns.localization.appearancereskinFonts = "Font style"
ns.localization.appearancereskinFontsTooltip = "Adjust global font style."
ns.localization.appearanceenableTheme = "Theme"
ns.localization.appearanceenableThemeTooltip = "Enable global dark theme."
ns.localization.appearancereskinQuestTracker = "Objective tracker"
ns.localization.appearancereskinPetBattle = "Pet battle"
ns.localization.appearancevignette = "Vignette"
ns.localization.appearancevignetteTooltip = "Add a shadow overlay to screen edge."
ns.localization.appearancevignetteAlpha = "intensity"
ns.localization.appearancereskinDBM = "DBM"
ns.localization.appearancereskinBW = "BigWigs"
ns.localization.appearancereskinWA = "WeakAuras"
ns.localization.appearancereskinPGF = "Premade Groups Filter"
ns.localization.appearancereskinSkada = "Skada"
ns.localization.appearancecolourScheme = "Colour scheme"
ns.localization.appearancecolourScheme1 = "Class colour"
ns.localization.appearancecolourScheme2 = "Custom"
ns.localization.appearancecolourScheme1Tooltip = "Automatically change the colour scheme based on your character's class."
ns.localization.appearancecolourScheme2Tooltip = "Click the square to the right to choose a custom colour."
ns.localization.appearancechooseColour = "Choose..."



ns.localization.automation = "Automation"
ns.localization.automationSubText = "With these features, the UI can perform common tasks automatically."
ns.localization.automationautoSellJunk = "Sell junk"
ns.localization.automationautoSellJunkTooltip = "Automatically sell grey quality items to vendors, unless they are used in an equipment set."
ns.localization.automationautoScreenShot = "Screenshot"
ns.localization.automationautoScreenShotTooltip = "Automatically takes a screenshot when you earn an achievement."
ns.localization.automationautoSetRole = "Skip unnecessary role poll popups"
ns.localization.automationautoSetRoleTooltip = "Skip the role poll popup if your role is already set or you are playing a pure dps class."
ns.localization.automationautoSetRole_useSpec = "Set role based on current specialization"
ns.localization.automationautoSetRole_useSpecTooltip = "Always attempt to set your role automatically based on your spec, never showing the popup."
ns.localization.automationautoSetRole_verbose = "Verbose mode"
ns.localization.automationautoSetRole_verboseTooltip = "Enable to be informed of what happens when the popup is skipped."
ns.localization.automationautoRepair = "Repair"
ns.localization.automationautoRepairTooltip = "Automatically repair your gear."
ns.localization.automationautoActionCam = "Action camera"
ns.localization.automationautoActionCamTooltip = "Automatically enable action camera mode."
ns.localization.automationautoQuest = "Quest"
ns.localization.automationautoQuestTooltip = "Automatically accept and deliver quests."
ns.localization.automationautoTabBinder = "Tab bind"
ns.localization.automationautoTabBinderTooltip = "Automatically change your TAB key binding to only target enemy playerswhen in PvP zones, and to target all enemies when not."
ns.localization.automationautoAcceptInvite = "Invite"
ns.localization.automationautoAcceptInviteTooltip = "Automatically accept invites from friends and guild members."
ns.localization.automationautoActionCam = "ActionCam"
ns.localization.automationautoActionCamTooltip = "Automatically enable action camera mode."





ns.localization.notification = "Notification"
ns.localization.notificationSubText = "These options let you choose when and how the UI should show notifications."
ns.localization.notificationalert = ""
ns.localization.notificationenableNotification = "Enable"
ns.localization.notificationenableNotificationTooltip = "Allow notifications to be shown. A banner will appear at the top of the UI."
ns.localization.notificationplaySounds = "Play sound"
ns.localization.notificationplaySoundsTooltip = "Play a sound when a notification is shown."
ns.localization.notificationcheckMail = "Mail"
ns.localization.notificationcheckMailTooltip = "Show a notification when you have new mail."
ns.localization.notificationcheckBagsFull = "Bags full"
ns.localization.notificationcheckBagsFullTooltip = "Show a notification when your bags are full."
ns.localization.notificationinterrupt = "Interrupt"
ns.localization.notificationinterruptTooltip = "Announce when you successfully interrupt."
ns.localization.notificationinterruptSound = "Sound"
ns.localization.notificationinterruptSoundTooltip = "Play a sound when you successfully interrupt."
ns.localization.notificationdispel = "Dispel"
ns.localization.notificationdispelTooltip = "Announce when you successfully Dispel."
ns.localization.notificationdispelSound = "Sound"
ns.localization.notificationdispelSoundTooltip = "Play a sound when you successfully Dispel."
ns.localization.notificationrare = "Rare"
ns.localization.notificationrareTooltip = "Rare alert."
ns.localization.notificationrareSound = "Sound"
ns.localization.notificationrareSoundTooltip = "Play a sound when a rare nearby."
ns.localization.notificationspell = "Spell"
ns.localization.notificationresurrect = "Resurrect"
ns.localization.notificationsapped = "Sap"
ns.localization.notificationspellTooltip = "Announce some important spells."
ns.localization.notificationresurrectTooltip = "Announce resurrect information."
ns.localization.notificationsappedTooltip = "Announce when a rogue saps you."




ns.localization.infobar = "Infobar"
ns.localization.infobarSubText = "The infobar is the panel at the top of the screen. \nMoving your mouse over it reveals additional functionality and information."
ns.localization.infobarenable = "Enable"
ns.localization.infobarmouseover = "Show blocks on mouseover"
ns.localization.infobarmouseoverTooltip = "Only show the blocks when moving the cursor over the menu bar."
ns.localization.infobarstats = "Time/FPS/Latency"
ns.localization.infobarstatsTooltip = "Show time/FPS/latency informations."
ns.localization.infobarmicroMenu = "Micro menu"
ns.localization.infobarmicroMenuTooltip = "Show game menu."
ns.localization.infobarskadaHelper = "Skada helper"
ns.localization.infobarskadaHelperTooltip = "Left click to toggle Skada panel\nRight click to hide Skada panel\nMiddle click to reset Skada data."
ns.localization.infobarspecTalent = "Talent/Spec"
ns.localization.infobarspecTalentTooltip = "Show talent and specialization\nLeft click to change specialization\nRight click to change loot specialization."
ns.localization.infobarfriends = "Friends"
ns.localization.infobarfriendsTooltip = "Show friends."
ns.localization.infobarcurrencies = "Currencies"
ns.localization.infobarcurrenciesTooltip = "Show currencies and count."
ns.localization.infobarreport = "Daily/weekly"
ns.localization.infobarreportTooltip = "Show daily weekly informations."
ns.localization.infobardurability = "Durability"
ns.localization.infobardurabilityTooltip = "Show gears durability."







ns.localization.actionbar = "Actionbar"
ns.localization.actionbarSubText = "These options are specific to the action bars and their buttons."
ns.localization.actionbarline_1 = ""
ns.localization.actionbarline_2 = ""
ns.localization.actionbarline_3 = ""
ns.localization.actionbarsGeneral = "Layout"
ns.localization.actionbarenable = "Enable"
ns.localization.actionbarenableTooltip = "Uncheck if you want to use another action bars addon."
ns.localization.actionbarlayoutStyle = "Layout style"
ns.localization.actionbarlayoutStyle1 = "Default (3*12)"
ns.localization.actionbarlayoutStyle2 = "Divide bar3 on side (2*18)"
ns.localization.actionbarlayoutStyle3 = "Only show bars on mouseover"
ns.localization.actionbarbuttonSizeNormal = "Button size normal"
ns.localization.actionbarbuttonSizeNormalTooltip = "Button size for main bar."
ns.localization.actionbarbuttonSizeSmall = "Button size small"
ns.localization.actionbarbuttonSizeSmallTooltip = "Button size for side bar."
ns.localization.actionbarbuttonSizeBig = "Button size big"
ns.localization.actionbarbuttonSizeBigTooltip = "Button size for stance bar."
ns.localization.actionbarbuttonSizeHuge = "Button size huge"
ns.localization.actionbarbuttonSizeHugeTooltip = "Button size for extra bar."
ns.localization.actionbarhotKey = "Show hotkey"
ns.localization.actionbarmacroName = "Show macro name"
ns.localization.actionbarcount = "Show item counts"
ns.localization.actionbarclassColor = "Class colour button border"
ns.localization.actionbarsenableStyle = "Button style"
ns.localization.actionbarsenableStyleTooltip = "You may need to disable this option to ensure compatibility with other action bars addons."
ns.localization.actionbarhoverBind = "Hover bind"
ns.localization.actionbarhoverBindTooltip = "Type /hb then bind buttons on mouseover."
ns.localization.actionbarsideBar = "Side bar"
ns.localization.actionbarsideBarTooltip = "Show side bar."
ns.localization.actionbarsideBarMouseover = "Side bar mouseover"
ns.localization.actionbarsideBarMouseoverTooltip = "Show side bar on mouseover."
ns.localization.actionbarpetBar = "Pet bar"
ns.localization.actionbarpetBarTooltip = "Show pet bar."
ns.localization.actionbarpetBarMouseover = "Pet bar mouseover"
ns.localization.actionbarpetBarMouseoverTooltip = "Show pet bar on mouseover."
ns.localization.actionbarstanceBar = "Stance bar"
ns.localization.actionbarstanceBarTooltip = "Show stance bar."
ns.localization.actionbarstanceBarMouseover = "Stance bar mouseover"
ns.localization.actionbarstanceBarMouseoverTooltip = "Show stance bar on mouseover."
ns.localization.actionbarbar3 = "Bar3"
ns.localization.actionbarbar3Tooltip = "Show bar3."
ns.localization.actionbarbar3Mouseover = "Bar3 mouseover"
ns.localization.actionbarbar3MouseoverTooltip = "Show bar3 on mouseover."


ns.localization.inventory = "Inventory"
ns.localization.inventorySubText = "Choose and customize a bag style of your liking."
ns.localization.inventoryGeneral = "General"
ns.localization.inventoryStyle = "Style-specific"
ns.localization.inventoryuseCategory = "Classify items by type"
ns.localization.inventoryreverseSort = "Reverse sort bags"
ns.localization.inventoryenable = "Enable"
ns.localization.inventoryenableTooltip = "Uncheck if you want to use another inventory addon."
ns.localization.inventorygearSetFilter = "Equipment set"
ns.localization.inventoryitemLevel = "Show item level"
ns.localization.inventorynewitemFlash = "New item flash"
ns.localization.inventoryitemSlotSize = 'Slot size'
ns.localization.inventorybagColumns = 'Columns'


ns.localization.tooltip = "Tooltip"
ns.localization.tooltipSubText = "Adjust the appearance and functionality of the game tooltip."
ns.localization.tooltipenable = "Enable tooltip"
ns.localization.tooltipenableTooltip = "Uncheck if you want to use another tooltip addon."
ns.localization.tooltipcursor = "Keeps the tooltip near cursor"
ns.localization.tooltiphidePVP = "Hide PVP status"
ns.localization.tooltiphideFaction = "Hide player faction"
ns.localization.tooltiphideTitle = "Hide player title"
ns.localization.tooltiphideRealm = "Hide player realm"
ns.localization.tooltiphideRank = "Hide player guild rank"
ns.localization.tooltipcombatHide = "Hide tooltip in combat"
ns.localization.tooltipborderColor = "Coloured by item quality"
ns.localization.tooltiptipIcon = "Show icon"
ns.localization.tooltiptipClear = "Clear useless informations"
ns.localization.tooltipilvlSpec = "Show item level and spec"
ns.localization.tooltiplinkHover = "Chat frame link hover"
ns.localization.tooltipextraInfo = "Show extra info"
ns.localization.tooltipazeriteTrait = "Show azerite armor info"




ns.localization.chat = "Chat"
ns.localization.chatSubText = "Adjust the appearance and functionality of the game chat."
ns.localization.chatenable = "Enable"
ns.localization.chatenableTooltip = "Uncheck if you want to use another chat addon."

ns.localization.chatlockPosition = "Lock position"
ns.localization.chatuseOutline = "Outline"
ns.localization.chatuseOutlineTooltip = "Add outline for chat text."
ns.localization.chatwhisperAlert = "Whisper alert"
ns.localization.chatwhisperAlertTooltip = "Add sound alert for whisper messages."
ns.localization.chattimeStamp = "Time stamp"
ns.localization.chattimeStampTooltip = "Add customized time stamp."
ns.localization.chatitemLink = "Item link"
ns.localization.chatitemLinkTooltip = "Expand item links in chat or when you or someone in your group receives loot to display item slot and item level."
ns.localization.chatspamageMeter = "Spamage meter"
ns.localization.chatspamageMeterTooltip = "Suppresses chat messages from damage meters."
ns.localization.chatchatButton = "Chat button"
ns.localization.chatchannelSticky = "Channel sticky"
ns.localization.chatlineFading = "Line fading"
ns.localization.chatuseFilter = "Chat filter"
ns.localization.chatuseFilterTooltip = "Enable chat filter."
ns.localization.chatautoBubble = "Chat bubble"
ns.localization.chatautoBubbleTooltip = "Only enable chat bubble in raid."



ns.localization.map = "Map"
ns.localization.mapSubText = "Adjust the appearance and functionality of the game maps."
ns.localization.mapline = ""
ns.localization.mapworldMap = "Enable world map"
ns.localization.mapworldMapTooltip = "Uncheck if you want to use another world map addon."
ns.localization.mapcoords = "Show coords"
ns.localization.mapcoordsTooltip = "Show player and cursor coords on world map."
ns.localization.mapmapReveal = "Map reveal"
ns.localization.mapmapRevealTooltip = "Reveals every portion of every zone of the world map."
ns.localization.mapminiMap = "Enable mini map"
ns.localization.mapminiMapTooltip = "Uncheck if you want to use another mini map addon."
ns.localization.mapwhoPings = "Show who pings"
ns.localization.mapwhoPingsTooltip = "Show who pings minimap."
ns.localization.mapminiMapSize = "Minimap size"





ns.localization.unitframe = "Unitframe"
ns.localization.unitframeSubText = "These options control most of the options for the unit frames."
ns.localization.unitframeenable = "Enable Unit frames"
ns.localization.unitframeenableTooltip = "Uncheck if you want to use another unit frames addon."
ns.localization.unitframeline = ""
ns.localization.unitframetransMode = "Transparency"
ns.localization.unitframetransModeTooltip = "Uncheck if you prefer traditional solid colour mode."
ns.localization.unitframecolourSmooth = "Colour smooth"
ns.localization.unitframecolourSmoothTooltip = "Color the health bar with a smooth gradient based on the current health percentage."

ns.localization.unitframeportrait = "Portrait"
ns.localization.unitframeportraitTooltip = "Add portrait on unitframes."
ns.localization.unitframehealer_layout = "Healer layout"
ns.localization.unitframehealer_layoutTooltip = "Symmetrical layout, more friendly for healers."
ns.localization.unitframeframeVisibility = "Clean mode"
ns.localization.unitframeframeVisibilityTooltip = "Only show player unitframe when player enter combat or have a target."
ns.localization.unitframethreat = "Threat"
ns.localization.unitframethreatTooltip = "Show threat indicator."
ns.localization.unitframerangeCheck = "Range fade"
ns.localization.unitframerangeCheckTooltip = "Changes the opacity of a unit frame based on whether the frame's unit is in the player's range."
ns.localization.unitframeoverAbsorb = "Absorb"
ns.localization.unitframeoverAbsorbTooltip = "Show damage absorb shield."
ns.localization.unitframehealPrediction = "Heal prediction"
ns.localization.unitframehealPredictionTooltip = "Show incoming heals."
ns.localization.unitframeclassPower = "Class power"
ns.localization.unitframeclassPowerTooltip = "Show player's class resources (like Chi Orbs or Holy Power) and combo points."
ns.localization.unitframedispellable = "Dispelable"
ns.localization.unitframedispellableTooltip = "Highlighting debuffs that are dispellable by the player."
ns.localization.unitframeenableCastbar = "Castbar"
ns.localization.unitframeenableCastbarTooltip = "Uncheck if you want to use another castbar addon."
ns.localization.unitframecastbar_separatePlayer = "Separate player castbar"
ns.localization.unitframecastbar_separateTarget = "Separate target castbar"
ns.localization.unitframeenableGroup = "Enable Party/Raid frames"
ns.localization.unitframeenableGroupTooltip = "Uncheck if you want to use another addon for party and raid frames."
ns.localization.unitframeshowGroupName = "Show names"
ns.localization.unitframeshowGroupNameTooltip = "Show group member names."
ns.localization.unitframecolourSmooth_Raid = "Colour smooth"
ns.localization.unitframecolourSmooth_RaidTooltip = "Color the raid health bar with a smooth gradient based on the current health percentage."
ns.localization.unitframecolourSmooth_Raid = "Colour smooth"
ns.localization.unitframecolourSmooth_RaidTooltip = "Color the boss health bar with a smooth gradient based on the current health percentage."
ns.localization.unitframeenableBoss = "Boss frames"
ns.localization.unitframeenableBossTooltip = "Enables boss frames, uncheck if you want to use another addon for boss frames."
ns.localization.unitframeenableArena = "Arena frames"
ns.localization.unitframeenableArenaTooltip = "Enables arena frames, uncheck if you want to use another addon for arena frames."
ns.localization.unitframedebuffbyPlayer = "Aura filter"
ns.localization.unitframedebuffbyPlayerTooltip = "Only show debuffs that casted by player on target unitframe."







ns.localization.classmod = "Class specific"
ns.localization.classmodSubText = "These options allow you to toggle the class-specific modules in the UI."

local classes = UnitSex("player") == 2 and LOCALIZED_CLASS_NAMES_MALE or LOCALIZED_CLASS_NAMES_FEMALE

for class, localized in pairs(classes) do
	ns.localization["classmod"..strlower(class)] = localized
end

ns.localization.classmodhavocFury = "|cffffffff Demon Hunter havoc fury"
ns.localization.classmodhavocFuryTooltip = "Change fury colour based on current value."

ns.localization.credits = "Credits"
ns.localization.thankYou = "Thank you:"
ns.localization.credits_1 = "Haleth, siweia"
ns.localization.credits_2 = "Haste, Tukz, Zork"
ns.localization.credits_3 = "|cff808080as well as...|r"
ns.localization.credits_4 = "Elv, Lightspark, Allez, AlleyKat\n\nCaellian, p3lim, Shantalya, tekkub\n\nTuller, Wildbreath, aduth, silverwind\n\nNibelheim, humfras, aliluya555, Paojy"


